# Generated by Django 5.2.17 on 2026-08-26 19:56

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inference", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GenerationJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("pillar_article", "Artigo pilar"),
                            ("qa_answer", "Resposta a pergunta"),
                            ("pdf_ingestion", "Conversao de PDF"),
                        ],
                        max_length=20,
                        verbose_name="tipo",
                    ),
                ),
                (
                    "target_object_id",
                    models.UUIDField(blank=True, null=True, verbose_name="objeto alvo"),
                ),
                (
                    "current_step",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="passo atual"
                    ),
                ),
                (
                    "total_steps",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="total de passos"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Aguardando"),
                            ("running", "Executando"),
                            ("waiting_capacity", "Aguardando capacidade"),
                            ("waiting_human", "Aguardando revisao humana"),
                            ("done", "Concluido"),
                            ("failed", "Falhou"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="situacao",
                    ),
                ),
                (
                    "step_payloads",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="resultados dos passos"
                    ),
                ),
                (
                    "attempt_count",
                    models.PositiveIntegerField(default=0, verbose_name="tentativas"),
                ),
                (
                    "last_error",
                    models.TextField(blank=True, verbose_name="ultimo erro"),
                ),
                (
                    "next_attempt_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="proxima tentativa"
                    ),
                ),
                (
                    "lease_token",
                    models.UUIDField(
                        blank=True, null=True, verbose_name="token da reserva"
                    ),
                ),
                (
                    "lease_expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="reserva expira em"
                    ),
                ),
                (
                    "idempotency_key",
                    models.UUIDField(
                        default=uuid.uuid4,
                        unique=True,
                        verbose_name="chave de idempotencia",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="criado em"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="concluido em"
                    ),
                ),
            ],
            options={
                "verbose_name": "trabalho de geracao",
                "verbose_name_plural": "trabalhos de geracao",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "next_attempt_at"],
                        name="ops_generat_status_00e0af_idx",
                    ),
                    models.Index(
                        fields=["kind", "status"], name="ops_generat_kind_8e7d17_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="InferenceLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("model_name", models.CharField(max_length=120, verbose_name="modelo")),
                ("workload", models.CharField(max_length=20, verbose_name="carga")),
                (
                    "input_tokens",
                    models.PositiveIntegerField(
                        default=0, verbose_name="tokens de entrada"
                    ),
                ),
                (
                    "output_tokens",
                    models.PositiveIntegerField(
                        default=0, verbose_name="tokens de saida"
                    ),
                ),
                (
                    "latency_ms",
                    models.PositiveIntegerField(
                        default=0, verbose_name="latencia (ms)"
                    ),
                ),
                (
                    "cost_brl",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        max_digits=10,
                        verbose_name="custo (BRL)",
                    ),
                ),
                (
                    "succeeded",
                    models.BooleanField(default=True, verbose_name="sucesso"),
                ),
                ("error", models.TextField(blank=True, verbose_name="erro")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="criado em"
                    ),
                ),
                (
                    "connection",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs",
                        to="inference.inferenceconnection",
                        verbose_name="conexao",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="ops.generationjob",
                        verbose_name="trabalho",
                    ),
                ),
            ],
            options={
                "verbose_name": "registro de inferencia",
                "verbose_name_plural": "registros de inferencia",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="ops_inferen_created_f37cb1_idx"
                    ),
                    models.Index(
                        fields=["model_name"], name="ops_inferen_model_n_c81c5a_idx"
                    ),
                ],
            },
        ),
    ]
