# Generated by Django 5.2.17 on 2026-08-29 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ops", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generationjob",
            name="kind",
            field=models.CharField(
                choices=[
                    ("pillar_article", "Artigo pilar"),
                    ("article_redraft", "Refazer secoes do artigo"),
                    ("article_replan", "Replanejar o artigo"),
                    ("qa_answer", "Resposta a pergunta"),
                    ("pdf_ingestion", "Conversao de PDF"),
                ],
                max_length=20,
                verbose_name="tipo",
            ),
        ),
    ]
