# Generated by Django 5.2.17 on 2026-09-25 23:25

import apps.editorial.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EditorialProfile",
            fields=[
                ("id", models.SmallAutoField(primary_key=True, serialize=False)),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("saude", "Saude e ciencia"),
                            ("negocio_local", "Negocio local"),
                            ("produto", "Produto ou SaaS"),
                            ("institucional", "Institucional"),
                        ],
                        default="saude",
                        max_length=20,
                        verbose_name="modo",
                    ),
                ),
                (
                    "tom_humor",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="serio (1) a engracado (5)",
                    ),
                ),
                (
                    "tom_formalidade",
                    models.PositiveSmallIntegerField(
                        default=3,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="formal (1) a casual (5)",
                    ),
                ),
                (
                    "tom_respeito",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="respeitoso (1) a irreverente (5)",
                    ),
                ),
                (
                    "tom_entusiasmo",
                    models.PositiveSmallIntegerField(
                        default=2,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="objetivo (1) a entusiasmado (5)",
                    ),
                ),
                (
                    "pessoa",
                    models.CharField(
                        default="voce",
                        help_text="Ex.: 'voce', 'o senhor', 'nos' (a equipe).",
                        max_length=40,
                        verbose_name="como falar com o leitor",
                    ),
                ),
                (
                    "regra_de_ouro",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="regra de ouro"
                    ),
                ),
                (
                    "somos",
                    models.JSONField(
                        blank=True, default=list, verbose_name="somos / nao somos"
                    ),
                ),
                (
                    "termos",
                    models.JSONField(
                        blank=True, default=list, verbose_name="termos proibidos"
                    ),
                ),
                (
                    "estruturas",
                    models.JSONField(
                        blank=True,
                        default=apps.editorial.models._estruturas_padrao,
                        verbose_name="estruturas",
                    ),
                ),
                (
                    "tipo_padrao",
                    models.CharField(
                        choices=[
                            ("guia", "Guia (o que e)"),
                            ("passo_a_passo", "Passo a passo"),
                            ("comparativo", "Comparativo (X ou Y)"),
                            ("lista", "Lista"),
                            ("custo", "Custo e preco"),
                            ("estudo_de_caso", "Estudo de caso"),
                            ("servico", "Servico (educativo)"),
                        ],
                        default="guia",
                        max_length=20,
                        verbose_name="tipo de conteudo padrao",
                    ),
                ),
                (
                    "convite",
                    models.TextField(
                        blank=True,
                        help_text="O que oferecer ao fim do texto, e como. Ex.: 'Convide para agendar uma avaliacao na clinica, sem pressao'. Vazio: o texto termina sem convite.",
                        verbose_name="convite final",
                    ),
                ),
                (
                    "exemplos",
                    models.TextField(
                        blank=True,
                        help_text="Dois ou tres paragrafos no tom desejado. Calibram melhor que adjetivos.",
                        verbose_name="paragrafos de exemplo",
                    ),
                ),
                (
                    "fundamentacao",
                    models.CharField(
                        choices=[
                            ("estrita", "Ideia central sempre com fonte do acervo"),
                            ("sem_fonte", "Permitir gerar sem fonte (desligado)"),
                        ],
                        default="estrita",
                        max_length=12,
                        verbose_name="fundamentacao",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
            ],
            options={
                "verbose_name": "perfil editorial",
                "verbose_name_plural": "perfil editorial",
            },
        ),
    ]
