# Generated by Django 5.2.17 on 2026-09-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("editorial", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="editorialprofile",
            name="oferta",
            field=models.TextField(
                blank=True,
                help_text="O que o site vende, em uma ou duas frases, como o cliente diria. Ex.: 'Assinatura mensal: voce manda as notas de material pelo WhatsApp e um engenheiro planilha os custos e diz se voce pagou caro'. E por ela que o PubliBot decide se um artigo leva chamada, e em que secao.",
                verbose_name="oferta do site",
            ),
        ),
    ]
