# Generated by Django 5.2.17 on 2026-09-27 16:13

from decimal import Decimal
from django.db import migrations, models


def copiar_para_o_negocio(apps, schema_editor):
    """O nicho do site vira o tema; a oferta do guia vai para o Negocio."""
    PerfilDoNegocio = apps.get_model("editorial", "PerfilDoNegocio")
    EditorialProfile = apps.get_model("editorial", "EditorialProfile")
    Site = apps.get_model("integrations", "Site")

    site = Site.objects.order_by("created_at").first()
    guia = EditorialProfile.objects.filter(pk=1).first()
    tema = (getattr(site, "niche", "") or "") if site else ""
    oferta = (guia.oferta or "") if guia else ""
    if tema or oferta:
        PerfilDoNegocio.objects.update_or_create(pk=1, defaults={"tema": tema, "oferta": oferta})


class Migration(migrations.Migration):

    dependencies = [
        ("editorial", "0002_oferta_do_site"),
        ("integrations", "0006_leitura_e_conversoes"),
    ]

    operations = [
        migrations.CreateModel(
            name="PerfilDoNegocio",
            fields=[
                ("id", models.SmallAutoField(primary_key=True, serialize=False)),
                (
                    "tema",
                    models.CharField(
                        blank=True,
                        help_text="Sobre o que o site escreve, numa frase. Ex.: 'Custos e orcamento de obra para quem constroi ou reforma a casa'.",
                        max_length=300,
                        verbose_name="tema do site",
                    ),
                ),
                (
                    "publico",
                    models.CharField(
                        blank=True,
                        help_text="Quem le e quem compra, numa frase. Ex.: 'Donos de obra de casa propria, sem formacao tecnica, que compram o material por conta'.",
                        max_length=300,
                        verbose_name="publico",
                    ),
                ),
                (
                    "oferta",
                    models.TextField(
                        blank=True,
                        help_text="O que o site vende, como o cliente diria. Ex.: 'Assinatura mensal: voce manda as notas de material pelo WhatsApp e um engenheiro planilha os custos e diz se voce pagou caro'.",
                        verbose_name="oferta",
                    ),
                ),
                (
                    "valor_da_conversao",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Quanto vale, em media, um contato que vira cliente (a primeira mensalidade, o ticket medio). Para calcular o retorno.",
                        max_digits=10,
                        null=True,
                        verbose_name="valor de uma conversao (R$)",
                    ),
                ),
                (
                    "investimento_publibot",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="investimento mensal no PubliBot (R$)",
                    ),
                ),
                (
                    "investimento_anuncios",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="O que vai para Google Ads e afins. Vazio: sem comparacao de custo.",
                        max_digits=10,
                        null=True,
                        verbose_name="investimento mensal em anuncios (R$)",
                    ),
                ),
                (
                    "cotacao_do_dolar",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("5.40"),
                        help_text="O custo por clique vem em dolar da DataForSEO.",
                        max_digits=6,
                        verbose_name="cotacao do dolar (R$)",
                    ),
                ),
            ],
            options={
                "verbose_name": "perfil do negocio",
                "verbose_name_plural": "perfil do negocio",
            },
        ),
        migrations.RunPython(copiar_para_o_negocio, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="editorialprofile",
            name="oferta",
        ),
    ]
