# Generated by Django 5.2.17 on 2026-09-27 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("editorial", "0003_perfil_do_negocio"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfildonegocio",
            name="frentes",
            field=models.TextField(
                blank=True,
                help_text="Servicos alem da oferta de entrada, um por linha: os que voce ja faz, e as oportunidades que o teste com artigo validou (entram por 'Validar', em Radar > Oportunidades). Contam como parte do negocio, e deixam de ser novidade.",
                verbose_name="frentes validadas",
            ),
        ),
    ]
