# Generated by Django 5.2.17 on 2026-10-05 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("editorial", "0004_frentes"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfildonegocio",
            name="nichos_de_dados",
            field=models.JSONField(
                blank=True, default=list, verbose_name="nichos de dados publicos"
            ),
        ),
    ]
