# Generated by Django 5.2.17 on 2026-08-25 18:39

import apps.accounts.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "schema_name",
                    models.CharField(
                        db_index=True,
                        max_length=63,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Use apenas letras minusculas, numeros e sublinhado, comecando por letra, entre 3 e 63 caracteres.",
                                regex="^[a-z][a-z0-9_]{2,62}$",
                            )
                        ],
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="nome")),
                (
                    "slug",
                    models.SlugField(max_length=63, unique=True, verbose_name="slug"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("provisioning", "Provisionando"),
                            ("active", "Ativo"),
                            ("suspended", "Suspenso"),
                            ("failed", "Falha no provisionamento"),
                        ],
                        db_index=True,
                        default="provisioning",
                        max_length=16,
                        verbose_name="situacao",
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="UTC", max_length=64, verbose_name="fuso horario"
                    ),
                ),
                (
                    "is_paused",
                    models.BooleanField(default=False, verbose_name="pausado"),
                ),
                (
                    "created_on",
                    models.DateField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "provisioned_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="provisionado em"
                    ),
                ),
                (
                    "provisioning_error",
                    models.TextField(
                        blank=True, verbose_name="erro de provisionamento"
                    ),
                ),
            ],
            options={
                "verbose_name": "tenant",
                "verbose_name_plural": "tenants",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="e-mail"
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="nome completo"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Proprietario"),
                            ("editor", "Editor"),
                            ("reviewer", "Revisor"),
                            ("viewer", "Leitor"),
                        ],
                        default="viewer",
                        help_text="Papel padrao. O papel efetivo por tenant vem do vinculo.",
                        max_length=16,
                        verbose_name="papel",
                    ),
                ),
                (
                    "is_technical_reviewer",
                    models.BooleanField(
                        default=False,
                        help_text="Habilita aprovar conteudo de saude, financas e afins (YMYL). Exige credencial profissional registrada.",
                        verbose_name="revisor tecnico",
                    ),
                ),
                (
                    "external_auth_provider",
                    models.CharField(
                        blank=True, max_length=32, verbose_name="provedor externo"
                    ),
                ),
                (
                    "external_subject_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="subject externo",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="criado em"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "usuario",
                "verbose_name_plural": "usuarios",
            },
            managers=[
                ("objects", apps.accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "domain",
                    models.CharField(db_index=True, max_length=253, unique=True),
                ),
                ("is_primary", models.BooleanField(db_index=True, default=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domains",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "dominio",
                "verbose_name_plural": "dominios",
            },
        ),
        migrations.CreateModel(
            name="TenantMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Proprietario"),
                            ("editor", "Editor"),
                            ("reviewer", "Revisor"),
                            ("viewer", "Leitor"),
                        ],
                        default="editor",
                        max_length=16,
                        verbose_name="papel",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="ativo")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="criado em"
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="accounts.tenant",
                        verbose_name="tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "vinculo com tenant",
                "verbose_name_plural": "vinculos com tenants",
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="accounts_us_email_74c8d6_idx"),
        ),
        migrations.AddIndex(
            model_name="tenantmembership",
            index=models.Index(
                fields=["user", "is_active"], name="accounts_te_user_id_c6cf37_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="tenantmembership",
            constraint=models.UniqueConstraint(
                fields=("tenant", "user"), name="uniq_membership_tenant_user"
            ),
        ),
    ]
