# Generated by Django 5.2.17 on 2026-10-05 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PedidoDeExclusao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=40, unique=True)),
                ("rede", models.CharField(max_length=20)),
                ("usuario_remoto", models.CharField(max_length=120)),
                (
                    "situacao",
                    models.CharField(
                        choices=[
                            ("feito", "Concluido"),
                            ("nada", "Nenhum dado encontrado"),
                        ],
                        max_length=10,
                    ),
                ),
                ("apagados", models.PositiveIntegerField(default=0)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-criado_em"],
            },
        ),
    ]
