# Generated by Django 5.2.17 on 2026-08-26 20:16

import apps.integrations.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="nome")),
                (
                    "slug",
                    models.SlugField(max_length=80, unique=True, verbose_name="slug"),
                ),
                (
                    "base_url",
                    models.URLField(
                        help_text="Somente https. Enderecos internos sao recusados.",
                        max_length=300,
                        validators=[apps.integrations.validators.validar_url_de_site],
                        verbose_name="endereco",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("django", "Django"),
                            ("wordpress", "WordPress"),
                            ("other", "Outra"),
                        ],
                        default="other",
                        max_length=16,
                        verbose_name="plataforma",
                    ),
                ),
                (
                    "api_key_ciphertext",
                    models.BinaryField(
                        blank=True, null=True, verbose_name="chave (cifrada)"
                    ),
                ),
                (
                    "api_key_fingerprint",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=64,
                        verbose_name="impressao da chave",
                    ),
                ),
                (
                    "api_key_last4",
                    models.CharField(
                        blank=True, max_length=4, verbose_name="ultimos 4"
                    ),
                ),
                (
                    "api_key_rotated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="rotacionada em"
                    ),
                ),
                (
                    "signing_secret_ciphertext",
                    models.BinaryField(
                        blank=True,
                        null=True,
                        verbose_name="segredo de assinatura (cifrado)",
                    ),
                ),
                (
                    "content_language",
                    models.CharField(
                        default="pt-br",
                        help_text="Idioma em que o site publica. Independe do idioma das fontes.",
                        max_length=10,
                        verbose_name="idioma de publicacao",
                    ),
                ),
                (
                    "site_timezone",
                    models.CharField(
                        default="America/Sao_Paulo",
                        max_length=64,
                        verbose_name="fuso horario",
                    ),
                ),
                (
                    "niche",
                    models.CharField(blank=True, max_length=200, verbose_name="nicho"),
                ),
                (
                    "is_sensitive",
                    models.BooleanField(
                        default=False,
                        help_text="Exige revisor com credencial tecnica para aprovar conteudo.",
                        verbose_name="tema sensivel",
                    ),
                ),
                (
                    "responsible_professional",
                    models.CharField(
                        blank=True,
                        help_text="Nome, registro no conselho e especialidade.",
                        max_length=200,
                        verbose_name="profissional responsavel",
                    ),
                ),
                (
                    "default_author",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="autor padrao"
                    ),
                ),
                (
                    "default_author_credentials",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="credenciais do autor"
                    ),
                ),
                (
                    "model_overrides",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="modelos por prompt"
                    ),
                ),
                (
                    "contract_version",
                    models.CharField(
                        blank=True, max_length=16, verbose_name="versao do contrato"
                    ),
                ),
                (
                    "capabilities",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Declarados pelo site em /api/v1/health/. O SaaS degrada conforme.",
                        verbose_name="recursos suportados",
                    ),
                ),
                (
                    "publishing_paused",
                    models.BooleanField(
                        default=False, verbose_name="publicacao pausada"
                    ),
                ),
                (
                    "max_articles_per_month",
                    models.PositiveSmallIntegerField(
                        default=8,
                        help_text="Volume alto e previsivel e o padrao que buscadores penalizam.",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(200),
                        ],
                        verbose_name="teto mensal de artigos",
                    ),
                ),
                (
                    "health_status",
                    models.CharField(
                        choices=[
                            ("unknown", "Desconhecida"),
                            ("healthy", "Saudavel"),
                            ("degraded", "Degradada"),
                            ("down", "Fora do ar"),
                        ],
                        default="unknown",
                        max_length=12,
                        verbose_name="saude",
                    ),
                ),
                (
                    "consecutive_failures",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="falhas seguidas"
                    ),
                ),
                (
                    "circuit_open_until",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="circuito aberto ate"
                    ),
                ),
                (
                    "last_success_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="ultimo sucesso"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="criado em"
                    ),
                ),
            ],
            options={
                "verbose_name": "site",
                "verbose_name_plural": "sites",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PublishAttempt",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "attempt_number",
                    models.PositiveSmallIntegerField(verbose_name="tentativa"),
                ),
                (
                    "payload_summary",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="resumo do envio"
                    ),
                ),
                (
                    "http_status",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="status"
                    ),
                ),
                (
                    "error_code",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="codigo do erro"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="mensagem"),
                ),
                (
                    "dry_run",
                    models.BooleanField(
                        default=False,
                        help_text="Payload montado e registrado, sem envio real.",
                        verbose_name="simulacao",
                    ),
                ),
                (
                    "succeeded",
                    models.BooleanField(default=False, verbose_name="sucesso"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="criada em"
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="publish_attempts_log",
                        to="content.article",
                        verbose_name="artigo",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="publish_attempts",
                        to="integrations.site",
                        verbose_name="site",
                    ),
                ),
            ],
            options={
                "verbose_name": "tentativa de publicacao",
                "verbose_name_plural": "tentativas de publicacao",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SiteApiCall",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("method", models.CharField(max_length=8, verbose_name="metodo")),
                ("path", models.CharField(max_length=200, verbose_name="rota")),
                (
                    "http_status",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="status"
                    ),
                ),
                (
                    "error_code",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="codigo do erro"
                    ),
                ),
                (
                    "latency_ms",
                    models.PositiveIntegerField(
                        default=0, verbose_name="latencia (ms)"
                    ),
                ),
                (
                    "request_bytes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="bytes enviados"
                    ),
                ),
                (
                    "idempotency_key",
                    models.UUIDField(
                        blank=True, null=True, verbose_name="chave de idempotencia"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="criada em"
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_calls",
                        to="integrations.site",
                        verbose_name="site",
                    ),
                ),
            ],
            options={
                "verbose_name": "chamada de API",
                "verbose_name_plural": "chamadas de API",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["site", "-created_at"],
                        name="integration_site_id_7dbbc0_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SitePost",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "remote_id",
                    models.CharField(max_length=120, verbose_name="id remoto"),
                ),
                ("title", models.CharField(max_length=300, verbose_name="titulo")),
                ("url", models.URLField(max_length=500, verbose_name="URL")),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="publicado em"
                    ),
                ),
                (
                    "primary_keyword",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="palavra-chave"
                    ),
                ),
                (
                    "word_count",
                    models.PositiveIntegerField(default=0, verbose_name="palavras"),
                ),
                (
                    "synced_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="sincronizado em",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="integrations.site",
                        verbose_name="site",
                    ),
                ),
            ],
            options={
                "verbose_name": "publicacao do site",
                "verbose_name_plural": "publicacoes do site",
                "ordering": ["-published_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("site", "remote_id"), name="uniq_post_por_site"
                    )
                ],
            },
        ),
    ]
