# Generated by Django 5.2.17 on 2026-08-26 20:34

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_question_answer_answercitation_and_more"),
        ("integrations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicationSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("weekly_slots", "Dias e horarios fixos"),
                            ("interval_days", "A cada N dias"),
                        ],
                        default="weekly_slots",
                        max_length=16,
                        verbose_name="modo",
                    ),
                ),
                (
                    "weekdays",
                    models.JSONField(
                        blank=True, default=list, verbose_name="dias da semana"
                    ),
                ),
                (
                    "times_of_day",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Lista de 'HH:MM' no fuso do site.",
                        verbose_name="horarios",
                    ),
                ),
                (
                    "interval_days",
                    models.PositiveSmallIntegerField(
                        default=7, verbose_name="intervalo em dias"
                    ),
                ),
                (
                    "max_per_day",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="maximo por dia"
                    ),
                ),
                (
                    "buffer_threshold",
                    models.PositiveSmallIntegerField(
                        default=2, verbose_name="reserva minima"
                    ),
                ),
                (
                    "qa_consumes_slot",
                    models.BooleanField(
                        default=True, verbose_name="resposta ocupa horario"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="ativa")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="criada em"
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule",
                        to="integrations.site",
                        verbose_name="site",
                    ),
                ),
            ],
            options={
                "verbose_name": "cadencia de publicacao",
                "verbose_name_plural": "cadencias de publicacao",
            },
        ),
        migrations.CreateModel(
            name="PublicationSlot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "slot_at",
                    models.DateTimeField(db_index=True, verbose_name="momento (UTC)"),
                ),
                (
                    "local_slot_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="momento local"
                    ),
                ),
                (
                    "filled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="preenchido em"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="criado em"
                    ),
                ),
                (
                    "answer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="slots",
                        to="content.answer",
                        verbose_name="resposta",
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="slots",
                        to="content.article",
                        verbose_name="artigo",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slots",
                        to="integrations.site",
                        verbose_name="site",
                    ),
                ),
            ],
            options={
                "verbose_name": "horario de publicacao",
                "verbose_name_plural": "horarios de publicacao",
                "ordering": ["slot_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("site", "slot_at"), name="uniq_horario_por_site"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("answer__isnull", True), ("article__isnull", False)
                            ),
                            models.Q(
                                ("answer__isnull", False), ("article__isnull", True)
                            ),
                            models.Q(
                                ("answer__isnull", True), ("article__isnull", True)
                            ),
                            _connector="OR",
                        ),
                        name="horario_com_artigo_ou_resposta",
                    ),
                ],
            },
        ),
    ]
