# Generated by Django 5.2.17 on 2026-08-29 12:06

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0006_answer_author"),
        ("integrations", "0002_publicationschedule_publicationslot"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthorPhotoDelivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "photo_sha256",
                    models.CharField(max_length=64, verbose_name="digest da foto"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("sent", "Entregue"),
                            ("failed", "Falhou"),
                        ],
                        default="pending",
                        max_length=12,
                        verbose_name="situacao",
                    ),
                ),
                (
                    "attempts",
                    models.PositiveIntegerField(default=0, verbose_name="tentativas"),
                ),
                (
                    "last_error",
                    models.TextField(blank=True, verbose_name="ultimo erro"),
                ),
                (
                    "remote_job_id",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        verbose_name="id do processamento remoto",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="criado em"
                    ),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="entregue em"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photo_deliveries",
                        to="content.author",
                        verbose_name="autor",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="author_photo_deliveries",
                        to="integrations.site",
                        verbose_name="site",
                    ),
                ),
            ],
            options={
                "verbose_name": "entrega de foto de autor",
                "verbose_name_plural": "entregas de foto de autor",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("site", "author", "photo_sha256"),
                        name="uniq_foto_por_site_e_autor",
                    )
                ],
            },
        ),
    ]
