# Generated by Django 5.2.17 on 2026-08-29 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0008_answer_origin"),
        ("integrations", "0003_authorphotodelivery"),
    ]

    operations = [
        migrations.AddField(
            model_name="publishattempt",
            name="answer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="publish_attempts_log",
                to="content.answer",
                verbose_name="resposta",
            ),
        ),
        migrations.AlterField(
            model_name="publishattempt",
            name="article",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="publish_attempts_log",
                to="content.article",
                verbose_name="artigo",
            ),
        ),
        migrations.AddConstraint(
            model_name="publishattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("answer__isnull", True), ("article__isnull", False)),
                    models.Q(("answer__isnull", False), ("article__isnull", True)),
                    _connector="OR",
                ),
                name="tentativa_de_artigo_ou_resposta",
            ),
        ),
    ]
