# Generated by Django 5.2.17 on 2026-09-27 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "integrations",
            "0004_publishattempt_answer_alter_publishattempt_article_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="context_synced_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="contexto atualizado em"
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="home_content_text",
            field=models.TextField(blank=True, verbose_name="texto da pagina inicial"),
        ),
    ]
