# Generated by Django 5.2.17 on 2026-09-27 14:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0005_site_context_synced_at_site_home_content_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="insights_synced_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="metricas coletadas em"
            ),
        ),
        migrations.CreateModel(
            name="ConversaoDoSite",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "external_id",
                    models.CharField(max_length=120, verbose_name="id no site"),
                ),
                ("dia", models.DateField(db_index=True, verbose_name="dia")),
                (
                    "tipo",
                    models.CharField(blank=True, max_length=40, verbose_name="tipo"),
                ),
                (
                    "via_cta",
                    models.BooleanField(
                        default=False, verbose_name="pela chamada do artigo"
                    ),
                ),
                (
                    "jornada",
                    models.JSONField(
                        blank=True, default=list, verbose_name="artigos lidos antes"
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversoes",
                        to="integrations.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "conversao",
                "verbose_name_plural": "conversoes",
                "ordering": ["-dia"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("site", "external_id"), name="uniq_conversao_por_site"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="LeituraDoDia",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "remote_id",
                    models.CharField(
                        db_index=True, max_length=120, verbose_name="id remoto"
                    ),
                ),
                ("dia", models.DateField(verbose_name="dia")),
                (
                    "views",
                    models.PositiveIntegerField(default=0, verbose_name="aberturas"),
                ),
                (
                    "engaged_views",
                    models.PositiveIntegerField(
                        default=0, verbose_name="leituras de verdade"
                    ),
                ),
                (
                    "engaged_seconds",
                    models.PositiveIntegerField(
                        default=0, verbose_name="segundos ativos"
                    ),
                ),
                (
                    "read_to_end",
                    models.PositiveIntegerField(
                        default=0, verbose_name="chegaram ao fim"
                    ),
                ),
                (
                    "cta_views",
                    models.PositiveIntegerField(
                        default=0, verbose_name="viram a chamada"
                    ),
                ),
                (
                    "cta_clicks",
                    models.PositiveIntegerField(
                        default=0, verbose_name="clicaram na chamada"
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leituras",
                        to="integrations.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "leitura do dia",
                "verbose_name_plural": "leituras do dia",
                "ordering": ["-dia"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("site", "remote_id", "dia"), name="uniq_leitura_por_dia"
                    )
                ],
            },
        ),
    ]
