# Generated by Django 5.2.17 on 2026-09-27 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0006_leitura_e_conversoes"),
        # O nicho e copiado para o tema do Negocio antes de sair daqui.
        ("editorial", "0003_perfil_do_negocio"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="site",
            name="niche",
        ),
    ]
