# Generated by Django 5.2.17 on 2026-09-27 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0007_sem_nicho"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversaodosite",
            name="canal_de_entrada",
            field=models.CharField(
                blank=True,
                choices=[
                    ("organic", "Busca organica"),
                    ("paid", "Anuncio"),
                    ("social", "Rede social"),
                    ("referral", "Outro site"),
                    ("email", "E-mail"),
                    ("direct", "Direto"),
                    ("other", "Outro"),
                ],
                max_length=10,
                verbose_name="primeira entrada",
            ),
        ),
        migrations.AddField(
            model_name="conversaodosite",
            name="canal_final",
            field=models.CharField(
                blank=True,
                choices=[
                    ("organic", "Busca organica"),
                    ("paid", "Anuncio"),
                    ("social", "Rede social"),
                    ("referral", "Outro site"),
                    ("email", "E-mail"),
                    ("direct", "Direto"),
                    ("other", "Outro"),
                ],
                max_length=10,
                verbose_name="ultima entrada",
            ),
        ),
    ]
