# Generated by Django 5.2.17 on 2026-09-27 22:16

from django.db import migrations, models


def para_contrato(apps, schema_editor):
    Site = apps.get_model("integrations", "Site")
    Site.objects.exclude(platform="wordpress").update(platform="contrato")


class Migration(migrations.Migration):
    dependencies = [
        # O autor do cadastro do site vira Autor padrao antes de sair daqui.
        ("content", "0018_autor_padrao"),
        ("integrations", "0008_canal_de_entrada"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="site",
            name="default_author",
        ),
        migrations.RemoveField(
            model_name="site",
            name="default_author_credentials",
        ),
        migrations.AlterField(
            model_name="site",
            name="platform",
            field=models.CharField(
                choices=[
                    ("contrato", "Rotas do contrato PubliBot (qualquer tecnologia)"),
                    ("wordpress", "WordPress, pela API do proprio WordPress (futuro)"),
                ],
                default="contrato",
                help_text="Rotas do contrato: o site (Django, Laravel, Node, o que for) implementa as rotas /api/v1 e o PubliBot chama. WordPress: o PubliBot publicaria pela API que o WordPress ja tem, sem instalar nada — ainda nao implementado.",
                max_length=16,
                verbose_name="integracao",
            ),
        ),
        migrations.RunPython(para_contrato, migrations.RunPython.noop),
    ]
