# Generated by Django 5.2.17 on 2026-08-26 20:25

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ReceivedPublication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("idempotency_key", models.UUIDField(db_index=True, unique=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("article", "Artigo"), ("qa", "Resposta")],
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=300)),
                ("slug", models.SlugField(blank=True, max_length=300)),
                ("html_content", models.TextField()),
                ("excerpt", models.TextField(blank=True)),
                ("meta_description", models.CharField(blank=True, max_length=160)),
                ("focus_keyword", models.CharField(blank=True, max_length=120)),
                ("language", models.CharField(default="pt-br", max_length=10)),
                ("author_name", models.CharField(blank=True, max_length=150)),
                ("author_credentials", models.CharField(blank=True, max_length=200)),
                ("reviewed_by", models.CharField(blank=True, max_length=150)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("content_disclosure", models.TextField(blank=True)),
                ("canonical_source", models.URLField(blank=True, max_length=500)),
                ("cover_image_url", models.URLField(blank=True, max_length=500)),
                ("cover_image_alt", models.CharField(blank=True, max_length=300)),
                (
                    "question_id",
                    models.CharField(blank=True, db_index=True, max_length=120),
                ),
                ("post_status", models.CharField(default="published", max_length=20)),
                ("publish_at", models.DateTimeField(blank=True, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name": "publicacao recebida",
                "verbose_name_plural": "publicacoes recebidas",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VisitorQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("question_text", models.TextField(max_length=500)),
                ("author_name", models.CharField(blank=True, max_length=150)),
                ("consent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "submitted_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("answered_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "pergunta de visitante",
                "verbose_name_plural": "perguntas de visitantes",
                "ordering": ["submitted_at"],
                "indexes": [
                    models.Index(
                        fields=["acknowledged_at", "answered_at"],
                        name="publibot_no_acknowl_3317ef_idx",
                    )
                ],
            },
        ),
    ]
