# Generated by Django 5.2.17 on 2026-08-29 12:09

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publibot_node", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthorPhoto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("author_reference", models.UUIDField(db_index=True, unique=True)),
                ("sha256", models.CharField(max_length=64)),
                ("image", models.ImageField(upload_to="autores/")),
                (
                    "received_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "foto de autor",
                "verbose_name_plural": "fotos de autor",
                "ordering": ["-received_at"],
            },
        ),
        migrations.AddField(
            model_name="receivedpublication",
            name="author_reference",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
