# Generated by Django 5.2.17 on 2026-09-27 15:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publibot_node", "0004_receivedpublication_version"),
    ]

    operations = [
        migrations.CreateModel(
            name="Conversao",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("dia", models.DateField(db_index=True)),
                ("kind", models.CharField(blank=True, max_length=40)),
                ("via_cta", models.BooleanField(default=False)),
                ("journey", models.JSONField(blank=True, default=list)),
                ("criada_em", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name": "conversao",
                "verbose_name_plural": "conversoes",
                "ordering": ["dia"],
            },
        ),
        migrations.AddField(
            model_name="receivedpublication",
            name="call_to_action",
            field=models.CharField(default="end", max_length=8),
        ),
        migrations.CreateModel(
            name="LeituraDoDia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dia", models.DateField()),
                ("views", models.PositiveIntegerField(default=0)),
                ("engaged_views", models.PositiveIntegerField(default=0)),
                ("engaged_seconds", models.PositiveIntegerField(default=0)),
                ("read_to_end", models.PositiveIntegerField(default=0)),
                ("cta_views", models.PositiveIntegerField(default=0)),
                ("cta_clicks", models.PositiveIntegerField(default=0)),
                (
                    "publicacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leituras",
                        to="publibot_node.receivedpublication",
                    ),
                ),
            ],
            options={
                "verbose_name": "leitura do dia",
                "verbose_name_plural": "leituras do dia",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("publicacao", "dia"), name="uniq_leitura_do_dia"
                    )
                ],
            },
        ),
    ]
