# Generated by Django 5.2.17 on 2026-09-27 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publibot_node", "0005_chamada_e_medicao"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversao",
            name="first_channel",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="conversao",
            name="last_channel",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="receivedpublication",
            name="related_articles",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
