# Generated by Django 5.2.17 on 2026-08-26 20:09

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("knowledge", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PromptTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        choices=[
                            ("metadata_extract", "Extracao de metadados"),
                            ("topic_ideation", "Geracao de pautas"),
                            ("consensus_filter", "Filtro de consenso"),
                            ("seo_draft", "Redacao"),
                            ("qa_answer", "Resposta a pergunta"),
                            ("image_prompt", "Prompt de imagem"),
                        ],
                        max_length=32,
                        unique=True,
                        verbose_name="chave",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="descricao")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="criado em"
                    ),
                ),
            ],
            options={
                "verbose_name": "modelo de prompt",
                "verbose_name_plural": "modelos de prompt",
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="PromptVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.PositiveSmallIntegerField(verbose_name="versao")),
                (
                    "variant",
                    models.CharField(
                        default="A", max_length=16, verbose_name="variante"
                    ),
                ),
                ("system_prompt", models.TextField(verbose_name="prompt de sistema")),
                (
                    "user_prompt_template",
                    models.TextField(
                        help_text="Aceita marcadores {chave} preenchidos em tempo de execucao.",
                        verbose_name="prompt do usuario",
                    ),
                ),
                (
                    "variables",
                    models.JSONField(
                        blank=True, default=list, verbose_name="variaveis esperadas"
                    ),
                ),
                (
                    "model_name",
                    models.CharField(blank=True, max_length=120, verbose_name="modelo"),
                ),
                (
                    "temperature",
                    models.FloatField(default=0.2, verbose_name="temperatura"),
                ),
                (
                    "max_tokens",
                    models.PositiveIntegerField(
                        default=4096, verbose_name="tokens maximos"
                    ),
                ),
                ("is_active", models.BooleanField(default=False, verbose_name="ativa")),
                (
                    "traffic_weight",
                    models.PositiveSmallIntegerField(
                        default=100,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="peso no sorteio",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="criada em"
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="content.prompttemplate",
                        verbose_name="modelo de prompt",
                    ),
                ),
            ],
            options={
                "verbose_name": "versao de prompt",
                "verbose_name_plural": "versoes de prompt",
                "ordering": ["template", "-version"],
            },
        ),
        migrations.CreateModel(
            name="PromptRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "input_tokens",
                    models.PositiveIntegerField(
                        default=0, verbose_name="tokens de entrada"
                    ),
                ),
                (
                    "output_tokens",
                    models.PositiveIntegerField(
                        default=0, verbose_name="tokens de saida"
                    ),
                ),
                (
                    "latency_ms",
                    models.PositiveIntegerField(
                        default=0, verbose_name="latencia (ms)"
                    ),
                ),
                (
                    "human_verdict",
                    models.CharField(
                        choices=[
                            ("pending", "Aguardando revisao"),
                            ("accepted", "Aceito sem alteracao"),
                            ("edited", "Aceito com edicao"),
                            ("rejected", "Rejeitado"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="veredito humano",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="criada em"
                    ),
                ),
                (
                    "prompt_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="runs",
                        to="content.promptversion",
                        verbose_name="versao",
                    ),
                ),
            ],
            options={
                "verbose_name": "execucao de prompt",
                "verbose_name_plural": "execucoes de prompt",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="titulo")),
                ("briefing", models.TextField(blank=True, verbose_name="orientacao")),
                (
                    "target_keyword",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="palavra-chave alvo"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("suggested", "Sugerida"),
                            ("approved", "Aprovada"),
                            ("rejected", "Rejeitada"),
                            ("used", "Usada"),
                        ],
                        default="suggested",
                        max_length=12,
                        verbose_name="situacao",
                    ),
                ),
                (
                    "cannibalization_score",
                    models.FloatField(
                        default=0.0, verbose_name="risco de canibalizacao"
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="aprovada em"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="criada em"
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_topics",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="aprovada por",
                    ),
                ),
            ],
            options={
                "verbose_name": "pauta",
                "verbose_name_plural": "pautas",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="titulo")),
                (
                    "slug",
                    models.SlugField(blank=True, max_length=300, verbose_name="slug"),
                ),
                (
                    "body_markdown",
                    models.TextField(blank=True, verbose_name="corpo (markdown)"),
                ),
                (
                    "body_html",
                    models.TextField(blank=True, verbose_name="corpo (html)"),
                ),
                ("excerpt", models.TextField(blank=True, verbose_name="resumo")),
                (
                    "meta_description",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="meta description"
                    ),
                ),
                (
                    "focus_keyword",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="palavra-chave"
                    ),
                ),
                (
                    "thesis_json",
                    models.JSONField(blank=True, default=dict, verbose_name="tese"),
                ),
                (
                    "consensus",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("high", "Concordancia alta"),
                            ("partial", "Concordancia parcial"),
                            ("conflict", "Fontes divergem"),
                        ],
                        max_length=10,
                        verbose_name="consenso",
                    ),
                ),
                (
                    "single_source",
                    models.BooleanField(default=False, verbose_name="fonte unica"),
                ),
                (
                    "outbound_link_url",
                    models.URLField(
                        blank=True, max_length=500, verbose_name="link de saida"
                    ),
                ),
                (
                    "anchor_text",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="texto-ancora"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("drafting", "Em producao"),
                            ("needs_more_sources", "Requer novas fontes"),
                            ("pending_review", "Aguardando revisao"),
                            ("approved_scheduled", "Aprovado e agendado"),
                            ("published", "Publicado"),
                            ("push_failed", "Falha na publicacao"),
                            ("rejected", "Rejeitado"),
                        ],
                        default="drafting",
                        max_length=24,
                        verbose_name="situacao",
                    ),
                ),
                (
                    "author_name",
                    models.CharField(blank=True, max_length=150, verbose_name="autor"),
                ),
                (
                    "author_credentials",
                    models.CharField(
                        blank=True,
                        help_text="Ex.: Enfermeira Obstetra, COREN-SP 123456",
                        max_length=200,
                        verbose_name="credenciais",
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="revisado em"
                    ),
                ),
                (
                    "review_seconds",
                    models.PositiveIntegerField(
                        default=0, verbose_name="segundos de revisao"
                    ),
                ),
                (
                    "human_edit_ratio",
                    models.FloatField(default=0.0, verbose_name="proporcao editada"),
                ),
                (
                    "word_count",
                    models.PositiveIntegerField(default=0, verbose_name="palavras"),
                ),
                (
                    "scheduled_for",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="agendado para",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="publicado em"
                    ),
                ),
                (
                    "published_url",
                    models.URLField(
                        blank=True, max_length=500, verbose_name="URL publicada"
                    ),
                ),
                (
                    "remote_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=120,
                        verbose_name="id remoto",
                    ),
                ),
                (
                    "idempotency_key",
                    models.UUIDField(
                        default=uuid.uuid4,
                        unique=True,
                        verbose_name="chave de idempotencia",
                    ),
                ),
                (
                    "publish_attempts",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="tentativas"
                    ),
                ),
                (
                    "last_publish_error",
                    models.TextField(blank=True, verbose_name="ultimo erro"),
                ),
                (
                    "last_error_code",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="codigo do erro"
                    ),
                ),
                (
                    "next_retry_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="proxima tentativa"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="criado em"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "primary_source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="primary_for_articles",
                        to="knowledge.document",
                        verbose_name="fonte primaria",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_articles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="revisado por",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="articles",
                        to="content.topic",
                        verbose_name="pauta",
                    ),
                ),
            ],
            options={
                "verbose_name": "artigo",
                "verbose_name_plural": "artigos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ArticleCitation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("rank", models.PositiveSmallIntegerField(verbose_name="posicao")),
                ("distance", models.FloatField(verbose_name="distancia")),
                (
                    "used_as_primary",
                    models.BooleanField(default=False, verbose_name="fonte primaria"),
                ),
                (
                    "source_title",
                    models.CharField(blank=True, max_length=500, verbose_name="titulo"),
                ),
                (
                    "source_url",
                    models.URLField(blank=True, max_length=500, verbose_name="URL"),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="citations",
                        to="content.article",
                        verbose_name="artigo",
                    ),
                ),
                (
                    "super_chunk",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="citations",
                        to="knowledge.superchunk",
                        verbose_name="trecho",
                    ),
                ),
            ],
            options={
                "verbose_name": "citacao",
                "verbose_name_plural": "citacoes",
                "ordering": ["article", "rank"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("article", "rank"), name="uniq_citacao_por_posicao"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ArticleRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.PositiveSmallIntegerField(verbose_name="versao")),
                ("body_markdown", models.TextField(verbose_name="corpo")),
                (
                    "source",
                    models.CharField(
                        choices=[("llm", "Modelo"), ("human", "Humano")],
                        max_length=8,
                        verbose_name="origem",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="criada em"
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="content.article",
                        verbose_name="artigo",
                    ),
                ),
                (
                    "editor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="editor",
                    ),
                ),
                (
                    "prompt_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="revisions",
                        to="content.promptrun",
                        verbose_name="execucao de prompt",
                    ),
                ),
            ],
            options={
                "verbose_name": "revisao de artigo",
                "verbose_name_plural": "revisoes de artigo",
                "ordering": ["article", "version"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("article", "version"), name="uniq_revisao_por_artigo"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="promptversion",
            constraint=models.UniqueConstraint(
                fields=("template", "version"), name="uniq_versao_por_template"
            ),
        ),
        migrations.AddConstraint(
            model_name="promptversion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("template", "variant"),
                name="uniq_variante_ativa_por_template",
            ),
        ),
        migrations.AddIndex(
            model_name="topic",
            index=models.Index(
                fields=["status", "-created_at"], name="content_top_status_9a5db1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["status", "scheduled_for"], name="content_art_status_3f8e78_idx"
            ),
        ),
    ]
