# Generated by Django 5.2.17 on 2026-08-26 20:34

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
        ("integrations", "0001_initial"),
        ("knowledge", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "remote_id",
                    models.CharField(max_length=120, verbose_name="id remoto"),
                ),
                (
                    "question_text",
                    models.TextField(max_length=500, verbose_name="pergunta"),
                ),
                (
                    "author_pseudonym",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="identificacao"
                    ),
                ),
                (
                    "consent_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Sem isto, o nome nao e exibido nem guardado.",
                        null=True,
                        verbose_name="consentimento em",
                    ),
                ),
                ("submitted_at", models.DateTimeField(verbose_name="enviada em")),
                (
                    "imported_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="importada em"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("imported", "Importada"),
                            ("needs_more_sources", "Requer novas fontes"),
                            ("drafting", "Em producao"),
                            ("pending_review", "Aguardando revisao"),
                            ("answered", "Respondida"),
                            ("discarded", "Descartada"),
                        ],
                        default="imported",
                        max_length=20,
                        verbose_name="situacao",
                    ),
                ),
                (
                    "best_similarity",
                    models.FloatField(
                        blank=True,
                        help_text="Menor distancia encontrada no acervo. Sustenta a regra do limiar.",
                        null=True,
                        verbose_name="melhor similaridade",
                    ),
                ),
                (
                    "retention_until",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Apos esta data o texto e a identificacao sao apagados.",
                        null=True,
                        verbose_name="reter ate",
                    ),
                ),
                (
                    "purged_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="expurgada em"
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="integrations.site",
                        verbose_name="site",
                    ),
                ),
            ],
            options={
                "verbose_name": "pergunta",
                "verbose_name_plural": "perguntas",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "body_markdown",
                    models.TextField(blank=True, verbose_name="corpo (markdown)"),
                ),
                (
                    "body_html",
                    models.TextField(blank=True, verbose_name="corpo (html)"),
                ),
                (
                    "outbound_link_url",
                    models.URLField(
                        blank=True, max_length=500, verbose_name="link de saida"
                    ),
                ),
                (
                    "anchor_text",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="texto-ancora"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("drafting", "Em producao"),
                            ("pending_review", "Aguardando revisao"),
                            ("approved_scheduled", "Aprovada e agendada"),
                            ("published", "Publicada"),
                            ("push_failed", "Falha na publicacao"),
                            ("rejected", "Rejeitada"),
                        ],
                        default="drafting",
                        max_length=24,
                        verbose_name="situacao",
                    ),
                ),
                (
                    "author_name",
                    models.CharField(blank=True, max_length=150, verbose_name="autor"),
                ),
                (
                    "author_credentials",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="credenciais"
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="revisada em"
                    ),
                ),
                (
                    "review_seconds",
                    models.PositiveIntegerField(
                        default=0, verbose_name="segundos de revisao"
                    ),
                ),
                (
                    "human_edit_ratio",
                    models.FloatField(default=0.0, verbose_name="proporcao editada"),
                ),
                (
                    "scheduled_for",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="agendada para",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="publicada em"
                    ),
                ),
                (
                    "published_url",
                    models.URLField(
                        blank=True, max_length=500, verbose_name="URL publicada"
                    ),
                ),
                (
                    "remote_id",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="id remoto"
                    ),
                ),
                (
                    "idempotency_key",
                    models.UUIDField(
                        default=uuid.uuid4,
                        unique=True,
                        verbose_name="chave de idempotencia",
                    ),
                ),
                (
                    "publish_attempts",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="tentativas"
                    ),
                ),
                (
                    "last_publish_error",
                    models.TextField(blank=True, verbose_name="ultimo erro"),
                ),
                (
                    "last_error_code",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="codigo do erro"
                    ),
                ),
                (
                    "next_retry_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="proxima tentativa"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="criada em"
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_answers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="revisada por",
                    ),
                ),
                (
                    "question",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answer",
                        to="content.question",
                        verbose_name="pergunta",
                    ),
                ),
            ],
            options={
                "verbose_name": "resposta",
                "verbose_name_plural": "respostas",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AnswerCitation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("rank", models.PositiveSmallIntegerField(verbose_name="posicao")),
                ("distance", models.FloatField(verbose_name="distancia")),
                (
                    "used_as_primary",
                    models.BooleanField(default=False, verbose_name="fonte primaria"),
                ),
                (
                    "source_title",
                    models.CharField(blank=True, max_length=500, verbose_name="titulo"),
                ),
                (
                    "source_url",
                    models.URLField(blank=True, max_length=500, verbose_name="URL"),
                ),
                (
                    "answer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="citations",
                        to="content.answer",
                        verbose_name="resposta",
                    ),
                ),
                (
                    "super_chunk",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="answer_citations",
                        to="knowledge.superchunk",
                        verbose_name="trecho",
                    ),
                ),
            ],
            options={
                "verbose_name": "citacao de resposta",
                "verbose_name_plural": "citacoes de resposta",
                "ordering": ["answer", "rank"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("answer", "rank"), name="uniq_citacao_resposta_posicao"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["status", "-submitted_at"], name="content_que_status_7b1c4d_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="question",
            constraint=models.UniqueConstraint(
                fields=("site", "remote_id"), name="uniq_pergunta_por_site"
            ),
        ),
        migrations.AddIndex(
            model_name="answer",
            index=models.Index(
                fields=["status", "scheduled_for"], name="content_ans_status_0e1b1c_idx"
            ),
        ),
    ]
