# Generated by Django 5.2.17 on 2026-08-29 00:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_question_answer_answercitation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="audience",
            field=models.CharField(blank=True, max_length=200, verbose_name="publico"),
        ),
        migrations.AddField(
            model_name="article",
            name="search_intent",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="intencao de busca"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="secondary_keywords",
            field=models.JSONField(
                blank=True, default=list, verbose_name="palavras-chave secundarias"
            ),
        ),
        migrations.CreateModel(
            name="ArticleSection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(verbose_name="ordem")),
                (
                    "level",
                    models.PositiveSmallIntegerField(default=2, verbose_name="nivel"),
                ),
                ("heading", models.CharField(max_length=200, verbose_name="titulo")),
                ("intent", models.TextField(blank=True, verbose_name="objetivo")),
                (
                    "keywords",
                    models.JSONField(
                        blank=True, default=list, verbose_name="palavras-chave"
                    ),
                ),
                (
                    "chunk_ids",
                    models.JSONField(blank=True, default=list, verbose_name="fontes"),
                ),
                ("body_markdown", models.TextField(blank=True, verbose_name="texto")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planejada"),
                            ("written", "Escrita"),
                            ("edited", "Editada por humano"),
                        ],
                        default="planned",
                        max_length=8,
                        verbose_name="situacao",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizada em"),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="content.article",
                        verbose_name="artigo",
                    ),
                ),
                (
                    "prompt_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sections",
                        to="content.promptrun",
                        verbose_name="execucao",
                    ),
                ),
            ],
            options={
                "verbose_name": "secao do artigo",
                "verbose_name_plural": "secoes do artigo",
                "ordering": ["article", "order"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("article", "order"), name="uniq_secao_artigo_ordem"
                    )
                ],
            },
        ),
    ]
