# Generated by Django 5.2.17 on 2026-08-29 11:59

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0004_alter_prompttemplate_key"),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="nome")),
                (
                    "photo",
                    models.ImageField(
                        blank=True, upload_to="autores/%Y/%m/", verbose_name="foto"
                    ),
                ),
                (
                    "credentials",
                    models.CharField(
                        blank=True,
                        help_text="Aparece na divulgacao de conteudo, junto de quem revisou.",
                        max_length=200,
                        verbose_name="credenciais",
                    ),
                ),
                ("bio", models.TextField(blank=True, verbose_name="mini biografia")),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="e-mail"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="telefone"
                    ),
                ),
                (
                    "social_links",
                    models.JSONField(
                        blank=True, default=list, verbose_name="links sociais"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="ativo")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="criado em"
                    ),
                ),
            ],
            options={
                "verbose_name": "autor",
                "verbose_name_plural": "autores",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="article",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="articles",
                to="content.author",
                verbose_name="autor",
            ),
        ),
    ]
