# Generated by Django 5.2.17 on 2026-08-29 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0006_answer_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="central_idea",
            field=models.TextField(blank=True, verbose_name="ideia central"),
        ),
        migrations.AddField(
            model_name="article",
            name="link_placement",
            field=models.CharField(
                choices=[("inline", "No meio do texto"), ("end", "So no final")],
                default="inline",
                max_length=8,
                verbose_name="posicao dos links",
            ),
        ),
        migrations.AddField(
            model_name="articlesection",
            name="carries_central_idea",
            field=models.BooleanField(
                default=False, verbose_name="sustenta a ideia central"
            ),
        ),
    ]
