# Generated by Django 5.2.17 on 2026-08-29 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0007_article_central_idea_article_link_placement_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="origin",
            field=models.CharField(
                choices=[
                    ("generated", "Gerada a partir do acervo"),
                    ("manual", "Escrita a mao"),
                ],
                default="generated",
                max_length=10,
                verbose_name="origem",
            ),
        ),
    ]
