# Generated by Django 5.2.17 on 2026-08-29 13:16

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0008_answer_origin"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "batch",
                    models.PositiveSmallIntegerField(default=1, verbose_name="lote"),
                ),
                ("order", models.PositiveSmallIntegerField(verbose_name="ordem")),
                (
                    "prompt",
                    models.TextField(blank=True, verbose_name="descricao usada"),
                ),
                (
                    "image",
                    models.ImageField(upload_to="capas/%Y/%m/", verbose_name="imagem"),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="texto alternativo"
                    ),
                ),
                (
                    "is_chosen",
                    models.BooleanField(default=False, verbose_name="escolhida"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="criada em"
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="content.article",
                        verbose_name="artigo",
                    ),
                ),
                (
                    "prompt_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="images",
                        to="content.promptrun",
                        verbose_name="execucao",
                    ),
                ),
            ],
            options={
                "verbose_name": "imagem do artigo",
                "verbose_name_plural": "imagens do artigo",
                "ordering": ["article", "batch", "order"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("article", "batch", "order"),
                        name="uniq_imagem_lote_ordem",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_chosen", True)),
                        fields=("article",),
                        name="uma_capa_escolhida_por_artigo",
                    ),
                ],
            },
        ),
    ]
