# Generated by Django 5.2.17 on 2026-09-25 17:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0009_articleimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleFaq",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="ordem"),
                ),
                ("question", models.CharField(max_length=300, verbose_name="pergunta")),
                ("answer", models.TextField(verbose_name="resposta")),
                (
                    "is_selected",
                    models.BooleanField(
                        default=False, verbose_name="incluir no artigo"
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        choices=[("llm", "Gerada"), ("human", "Escrita por humano")],
                        default="llm",
                        max_length=8,
                        verbose_name="origem",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizada em"),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faq",
                        to="content.article",
                        verbose_name="artigo",
                    ),
                ),
            ],
            options={
                "verbose_name": "pergunta frequente",
                "verbose_name_plural": "perguntas frequentes",
                "ordering": ["article", "order", "question"],
            },
        ),
    ]
