# Generated by Django 5.2.17 on 2026-09-25 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0010_articlefaq"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="content_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("guia", "Guia (o que e)"),
                    ("passo_a_passo", "Passo a passo"),
                    ("comparativo", "Comparativo (X ou Y)"),
                    ("lista", "Lista"),
                    ("custo", "Custo e preco"),
                    ("estudo_de_caso", "Estudo de caso"),
                    ("servico", "Servico (educativo)"),
                ],
                max_length=20,
                verbose_name="tipo de conteudo",
            ),
        ),
        migrations.AddField(
            model_name="topic",
            name="content_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("guia", "Guia (o que e)"),
                    ("passo_a_passo", "Passo a passo"),
                    ("comparativo", "Comparativo (X ou Y)"),
                    ("lista", "Lista"),
                    ("custo", "Custo e preco"),
                    ("estudo_de_caso", "Estudo de caso"),
                    ("servico", "Servico (educativo)"),
                ],
                max_length=20,
                verbose_name="tipo de conteudo",
            ),
        ),
    ]
