# Generated by Django 5.2.17 on 2026-09-25 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0011_article_content_type_topic_content_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="answercitation",
            name="citation_mode",
            field=models.CharField(
                default="link", max_length=12, verbose_name="como citar"
            ),
        ),
        migrations.AddField(
            model_name="answercitation",
            name="source_label",
            field=models.CharField(blank=True, max_length=300, verbose_name="rotulo"),
        ),
        migrations.AddField(
            model_name="articlecitation",
            name="citation_mode",
            field=models.CharField(
                default="link", max_length=12, verbose_name="como citar"
            ),
        ),
        migrations.AddField(
            model_name="articlecitation",
            name="source_label",
            field=models.CharField(blank=True, max_length=300, verbose_name="rotulo"),
        ),
    ]
