# Generated by Django 5.2.17 on 2026-09-26 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0012_answercitation_citation_mode_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="demand_score",
            field=models.FloatField(
                blank=True, null=True, verbose_name="nota do radar"
            ),
        ),
        migrations.AddField(
            model_name="topic",
            name="evidence",
            field=models.JSONField(blank=True, default=dict, verbose_name="evidencia"),
        ),
        migrations.AddField(
            model_name="topic",
            name="origin",
            field=models.CharField(
                choices=[("manual", "Criada a mao"), ("radar", "Sugerida pelo radar")],
                default="manual",
                max_length=8,
                verbose_name="origem",
            ),
        ),
    ]
