# Generated by Django 5.2.17 on 2026-09-26 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0013_topic_demand_score_topic_evidence_topic_origin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topic",
            name="status",
            field=models.CharField(
                choices=[
                    ("suggested", "Sugerida"),
                    ("approved", "Aprovada"),
                    ("waiting_sources", "Aguardando fontes"),
                    ("rejected", "Rejeitada"),
                    ("used", "Usada"),
                ],
                default="suggested",
                max_length=16,
                verbose_name="situacao",
            ),
        ),
    ]
