# Generated by Django 5.2.17 on 2026-09-26 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0014_alter_topic_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prompttemplate",
            name="key",
            field=models.CharField(
                choices=[
                    ("metadata_extract", "Extracao de metadados"),
                    ("topic_ideation", "Geracao de pautas"),
                    ("consensus_filter", "Filtro de consenso"),
                    ("article_outline", "Plano do artigo"),
                    ("section_draft", "Redacao de secao"),
                    ("article_framing", "Abertura e fecho"),
                    ("seo_metadata", "Metadados de busca"),
                    ("seo_draft", "Redacao (caminho antigo)"),
                    ("qa_answer", "Resposta a pergunta"),
                    ("opportunity_brief", "Descricao de oportunidade"),
                    ("seed_suggestion", "Sugestao de sementes e dores"),
                    ("image_prompt", "Prompt de imagem"),
                ],
                max_length=32,
                unique=True,
                verbose_name="chave",
            ),
        ),
    ]
