# Generated by Django 5.2.17 on 2026-09-27 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0015_alter_prompttemplate_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="previous_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="next_versions",
                to="content.article",
                verbose_name="versao anterior",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="update_notes",
            field=models.TextField(blank=True, verbose_name="o que atualizar"),
        ),
        migrations.AddField(
            model_name="article",
            name="version_number",
            field=models.PositiveSmallIntegerField(default=1, verbose_name="versao"),
        ),
        migrations.AlterField(
            model_name="article",
            name="status",
            field=models.CharField(
                choices=[
                    ("drafting", "Em producao"),
                    ("needs_more_sources", "Requer novas fontes"),
                    ("pending_review", "Aguardando revisao"),
                    ("approved_scheduled", "Aprovado e agendado"),
                    ("published", "Publicado"),
                    ("push_failed", "Falha na publicacao"),
                    ("rejected", "Rejeitado"),
                    ("superseded", "Substituido por versao nova"),
                ],
                default="drafting",
                max_length=24,
                verbose_name="situacao",
            ),
        ),
    ]
