# Generated by Django 5.2.17 on 2026-09-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0016_versoes_de_artigo"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="call_to_action",
            field=models.CharField(
                choices=[
                    ("none", "Nenhuma: o tema esta longe da oferta"),
                    ("end", "So no fim do artigo"),
                    ("inline", "No meio, onde o problema encontra a oferta, e no fim"),
                ],
                default="end",
                max_length=8,
                verbose_name="chamada para a oferta",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="call_to_action_after",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="chamada depois da secao"
            ),
        ),
        migrations.AddField(
            model_name="topic",
            name="call_to_action",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Decidir pelo tema"),
                    ("none", "Nenhuma: o tema esta longe da oferta"),
                    ("end", "So no fim do artigo"),
                    ("inline", "No meio, onde o problema encontra a oferta, e no fim"),
                ],
                max_length=8,
                verbose_name="chamada para a oferta",
            ),
        ),
    ]
