# Generated by Django 5.2.17 on 2026-09-27 22:16

from django.db import migrations, models


def autor_do_site_vira_padrao(apps, schema_editor):
    """O autor que estava no cadastro do site vira um Autor marcado como padrao."""
    Author = apps.get_model("content", "Author")
    Site = apps.get_model("integrations", "Site")

    site = Site.objects.order_by("created_at").first()
    nome = (getattr(site, "default_author", "") or "").strip() if site else ""
    if not nome or Author.objects.filter(padrao=True).exists():
        return
    autor = Author.objects.filter(name=nome).first()
    if autor is None:
        autor = Author.objects.create(
            name=nome, credentials=(site.default_author_credentials or "").strip()
        )
    autor.padrao = True
    autor.save(update_fields=["padrao"])


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0008_canal_de_entrada"),
        ("content", "0017_chamada_para_a_oferta"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="padrao",
            field=models.BooleanField(
                default=False,
                help_text="Assina o que for gerado sem autor escolhido. So um autor e o padrao.",
                verbose_name="autor padrao",
            ),
        ),
        migrations.RunPython(autor_do_site_vira_padrao, migrations.RunPython.noop),
    ]
