# Generated by Django 5.2.17 on 2026-09-30 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0018_autor_padrao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topic",
            name="origin",
            field=models.CharField(
                choices=[
                    ("manual", "Criada a mao"),
                    ("radar", "Sugerida pelo radar"),
                    ("link", "Link quebrado de outro site"),
                ],
                default="manual",
                max_length=8,
                verbose_name="origem",
            ),
        ),
    ]
