# Generated by Django 5.2.17 on 2026-09-30 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0019_link_quebrado_acompanhamento"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="artigo_parecido",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="content.article",
                verbose_name="artigo publicado parecido",
            ),
        ),
    ]
