# Generated by Django 5.2.17 on 2026-10-01 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0022_dois_fluxos"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="topic",
            name="fluxo",
        ),
        migrations.AddField(
            model_name="article",
            name="fluxo",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "A · Fontes curadas"),
                    ("pesquisa", "B · Pesquisa cientifica"),
                ],
                default="",
                max_length=10,
                verbose_name="fluxo",
            ),
        ),
    ]
