# Generated by Django 5.2.17 on 2026-10-02 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0024_texto_da_chamada"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="indexacao",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="indexacao no Google"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="indexacao_conferida_em",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                null=True,
                verbose_name="indexacao conferida em",
            ),
        ),
    ]
