# Generated by Django 5.2.17 on 2026-10-03 00:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0025_indexacao_no_google"),
        ("dados", "0001_catalogo"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="dados_usados",
            field=models.JSONField(
                blank=True, default=list, verbose_name="dados publicos usados"
            ),
        ),
        migrations.CreateModel(
            name="DadoDaPauta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "local",
                    models.CharField(
                        default="Brasil", max_length=120, verbose_name="local"
                    ),
                ),
                ("criado_em", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "serie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="dados.serie",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dados",
                        to="content.topic",
                    ),
                ),
            ],
            options={
                "ordering": ["criado_em"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("topic", "serie", "local"), name="uniq_dado_da_pauta"
                    )
                ],
            },
        ),
    ]
