# Generated by Django 5.2.17 on 2026-10-03 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0026_dados_publicos"),
    ]

    operations = [
        migrations.AddField(
            model_name="dadodapauta",
            name="automatico",
            field=models.BooleanField(default=False, verbose_name="entrou sozinho"),
        ),
        migrations.AddField(
            model_name="dadodapauta",
            name="tirado",
            field=models.BooleanField(default=False, verbose_name="tirado"),
        ),
    ]
