# Generated by Django 5.2.17 on 2026-10-03 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0027_dados_automaticos"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="pesquisa",
            field=models.JSONField(blank=True, default=dict, verbose_name="pesquisa"),
        ),
    ]
