# Generated by Django 5.2.17 on 2026-10-03 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0028_pesquisa_da_pergunta"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="conferencia_citacoes",
            field=models.JSONField(
                blank=True, default=list, verbose_name="conferencia das citacoes"
            ),
        ),
        migrations.AddField(
            model_name="articlesection",
            name="citacoes_conferidas",
            field=models.BooleanField(default=True, verbose_name="citacoes conferidas"),
        ),
        migrations.AlterField(
            model_name="prompttemplate",
            name="key",
            field=models.CharField(
                choices=[
                    ("metadata_extract", "Extracao de metadados"),
                    ("topic_ideation", "Geracao de pautas"),
                    ("consensus_filter", "Filtro de consenso"),
                    ("article_outline", "Plano do artigo"),
                    ("section_draft", "Redacao de secao"),
                    ("article_framing", "Abertura e fecho"),
                    ("seo_metadata", "Metadados de busca"),
                    ("seo_draft", "Redacao (caminho antigo)"),
                    ("qa_answer", "Resposta a pergunta"),
                    ("opportunity_brief", "Descricao de oportunidade"),
                    ("seed_suggestion", "Sugestao de sementes e dores"),
                    ("image_prompt", "Prompt de imagem"),
                    ("source_queries", "Outras palavras para buscar fontes"),
                    ("research_hypotheses", "Pesquisa: paragrafos hipoteticos"),
                    ("research_synthesis", "Pesquisa: sintese de um angulo"),
                    ("call_to_action_copy", "Texto da chamada para a oferta"),
                    ("citation_check", "Conferencia: a fonte sustenta a frase?"),
                    ("citation_fix", "Conferencia: reescrever a frase sem fonte"),
                ],
                max_length=32,
                unique=True,
                verbose_name="chave",
            ),
        ),
    ]
