# Generated by Django 5.2.17 on 2026-10-07 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0029_conferencia_de_citacoes"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="debate",
            field=models.JSONField(blank=True, default=dict, verbose_name="debate"),
        ),
        migrations.AlterField(
            model_name="topic",
            name="origin",
            field=models.CharField(
                choices=[
                    ("manual", "Criada a mao"),
                    ("radar", "Sugerida pelo radar"),
                    ("link", "Link quebrado de outro site"),
                    ("ideia", "Da caixa de ideias"),
                ],
                default="manual",
                max_length=8,
                verbose_name="origem",
            ),
        ),
    ]
