# Generated by Django 5.2.17 on 2026-10-03 00:42

import django.db.models.deletion
import django.utils.timezone
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Instituicao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sigla",
                    models.CharField(max_length=40, unique=True, verbose_name="sigla"),
                ),
                ("nome", models.CharField(max_length=200, verbose_name="nome")),
                (
                    "site",
                    models.URLField(blank=True, max_length=300, verbose_name="site"),
                ),
                (
                    "dominios",
                    models.JSONField(blank=True, default=list, verbose_name="dominios"),
                ),
                (
                    "nichos",
                    models.JSONField(blank=True, default=list, verbose_name="nichos"),
                ),
                (
                    "adaptador",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "sem adaptador"),
                            ("ibge", "IBGE (SIDRA)"),
                            ("bcb", "Banco Central (SGS)"),
                        ],
                        max_length=20,
                        verbose_name="adaptador",
                    ),
                ),
                (
                    "confiavel",
                    models.BooleanField(default=False, verbose_name="confiavel"),
                ),
                (
                    "notas",
                    models.TextField(
                        blank=True, verbose_name="o que tem e como chegar"
                    ),
                ),
                ("criada_em", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name": "instituicao",
                "verbose_name_plural": "instituicoes",
                "ordering": ["sigla"],
            },
        ),
        migrations.CreateModel(
            name="PedidoDeAdaptador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dominio",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="dominio"
                    ),
                ),
                (
                    "exemplos",
                    models.JSONField(
                        blank=True, default=list, verbose_name="links de exemplo"
                    ),
                ),
                (
                    "citacoes",
                    models.PositiveIntegerField(default=0, verbose_name="citacoes"),
                ),
                (
                    "situacao",
                    models.CharField(
                        choices=[
                            ("aberto", "Aberto"),
                            ("feito", "Feito"),
                            ("descartado", "Descartado"),
                        ],
                        default="aberto",
                        max_length=10,
                        verbose_name="situacao",
                    ),
                ),
                ("notas", models.TextField(blank=True, verbose_name="notas")),
                ("criado_em", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "atualizado_em",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "ordering": ["-citacoes"],
            },
        ),
        migrations.CreateModel(
            name="Serie",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("codigo", models.CharField(max_length=120, verbose_name="codigo")),
                ("titulo", models.CharField(max_length=300, verbose_name="titulo")),
                ("descricao", models.TextField(blank=True, verbose_name="descricao")),
                (
                    "unidade",
                    models.CharField(blank=True, max_length=60, verbose_name="unidade"),
                ),
                (
                    "recortes",
                    models.JSONField(blank=True, default=list, verbose_name="recortes"),
                ),
                (
                    "periodicidade",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="periodicidade"
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True, max_length=500, verbose_name="endereco"
                    ),
                ),
                (
                    "nichos",
                    models.JSONField(blank=True, default=list, verbose_name="nichos"),
                ),
                (
                    "situacao",
                    models.CharField(
                        choices=[
                            ("sugerida", "Sugerida"),
                            ("aprovada", "Aprovada"),
                            ("recusada", "Recusada"),
                        ],
                        default="sugerida",
                        max_length=10,
                        verbose_name="situacao",
                    ),
                ),
                (
                    "origem",
                    models.CharField(
                        choices=[
                            ("semente", "Semente"),
                            ("catalogo", "Catalogo da instituicao"),
                            ("acervo", "Citada no acervo"),
                            ("manual", "Cadastrada a mao"),
                        ],
                        max_length=10,
                        verbose_name="origem",
                    ),
                ),
                (
                    "citacoes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="citacoes no acervo"
                    ),
                ),
                (
                    "vetor",
                    pgvector.django.vector.VectorField(
                        blank=True, dimensions=1024, null=True, verbose_name="vetor"
                    ),
                ),
                ("criada_em", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "instituicao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="series",
                        to="dados.instituicao",
                    ),
                ),
            ],
            options={
                "verbose_name": "serie",
                "verbose_name_plural": "series",
                "ordering": ["instituicao__sigla", "titulo"],
            },
        ),
        migrations.CreateModel(
            name="Valor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "local",
                    models.CharField(
                        default="Brasil", max_length=120, verbose_name="local"
                    ),
                ),
                ("periodo", models.CharField(max_length=40, verbose_name="periodo")),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=6, max_digits=24, verbose_name="valor"
                    ),
                ),
                (
                    "nota",
                    models.CharField(blank=True, max_length=300, verbose_name="nota"),
                ),
                ("buscado_em", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "serie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="valores",
                        to="dados.serie",
                    ),
                ),
            ],
            options={
                "ordering": ["-periodo"],
            },
        ),
        migrations.AddConstraint(
            model_name="serie",
            constraint=models.UniqueConstraint(
                fields=("instituicao", "codigo"), name="uniq_serie_por_codigo"
            ),
        ),
        migrations.AddConstraint(
            model_name="valor",
            constraint=models.UniqueConstraint(
                fields=("serie", "local", "periodo"), name="uniq_valor_por_periodo"
            ),
        ),
    ]
