# Generated by Django 5.2.17 on 2026-10-04 14:33

from django.db import migrations, models


def ligar_adaptador_da_oms(apps, schema_editor):
    """A instituicao ja semeada ganha o adaptador (o deploy so cria o que falta)."""
    Instituicao = apps.get_model("dados", "Instituicao")
    Instituicao.objects.filter(sigla="OMS", adaptador="").update(adaptador="oms")


class Migration(migrations.Migration):

    dependencies = [
        ("dados", "0001_catalogo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instituicao",
            name="adaptador",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "sem adaptador"),
                    ("ibge", "IBGE (SIDRA)"),
                    ("bcb", "Banco Central (SGS)"),
                    ("oms", "OMS (Global Health Observatory)"),
                ],
                max_length=20,
                verbose_name="adaptador",
            ),
        ),
        migrations.RunPython(ligar_adaptador_da_oms, migrations.RunPython.noop),
    ]
