# Generated by Django 5.2.17 on 2026-08-26 19:44

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import pgvector.django.indexes
import pgvector.django.vector
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="nome")),
                (
                    "slug",
                    models.SlugField(max_length=80, unique=True, verbose_name="slug"),
                ),
                ("description", models.TextField(blank=True, verbose_name="descricao")),
                (
                    "default_prompt_hint",
                    models.TextField(
                        blank=True,
                        help_text="Texto injetado no prompt ao usar fontes desta categoria.",
                        verbose_name="orientacao para o prompt",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="criado em"
                    ),
                ),
            ],
            options={
                "verbose_name": "categoria de documento",
                "verbose_name_plural": "categorias de documento",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="RetrievalQuery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        choices=[("article", "Artigo"), ("qa", "Pergunta e resposta")],
                        max_length=10,
                        verbose_name="origem",
                    ),
                ),
                ("query_text", models.TextField(verbose_name="texto da consulta")),
                (
                    "top_k",
                    models.PositiveSmallIntegerField(default=3, verbose_name="top k"),
                ),
                ("max_distance", models.FloatField(verbose_name="distancia maxima")),
                (
                    "embedding_model",
                    models.CharField(blank=True, max_length=120, verbose_name="modelo"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="criado em"
                    ),
                ),
            ],
            options={
                "verbose_name": "consulta de recuperacao",
                "verbose_name_plural": "consultas de recuperacao",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "original_file",
                    models.FileField(
                        upload_to="documents/%Y/%m/", verbose_name="arquivo"
                    ),
                ),
                (
                    "file_sha256",
                    models.CharField(
                        db_index=True, max_length=64, unique=True, verbose_name="sha256"
                    ),
                ),
                (
                    "file_size_bytes",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="tamanho em bytes"
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=500, verbose_name="titulo"),
                ),
                (
                    "authors",
                    models.CharField(
                        blank=True,
                        help_text="Formatado para citacao: 'Sobrenome et al.' a partir de 3 autores.",
                        max_length=300,
                        verbose_name="autores",
                    ),
                ),
                (
                    "authors_raw",
                    models.JSONField(
                        blank=True, default=list, verbose_name="autores (bruto)"
                    ),
                ),
                (
                    "year",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1500),
                            django.core.validators.MaxValueValidator(2200),
                        ],
                        verbose_name="ano",
                    ),
                ),
                (
                    "doi",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="DOI",
                    ),
                ),
                (
                    "source_url",
                    models.URLField(
                        blank=True,
                        help_text="Usada como destino do link de saida. Confirmada por um humano.",
                        max_length=500,
                        verbose_name="URL de origem",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        blank=True,
                        help_text="Idioma da fonte (pode diferir do idioma de publicacao).",
                        max_length=10,
                        verbose_name="idioma",
                    ),
                ),
                (
                    "metadata_confidence",
                    models.CharField(
                        choices=[
                            ("auto", "Extraido automaticamente"),
                            ("crossref", "Confirmado no Crossref"),
                            ("manual", "Informado por humano"),
                        ],
                        default="auto",
                        max_length=12,
                        verbose_name="confianca dos metadados",
                    ),
                ),
                (
                    "authority_score",
                    models.PositiveSmallIntegerField(
                        default=50,
                        help_text="Usado para escolher a fonte primaria entre varias.",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="autoridade",
                    ),
                ),
                (
                    "content_fingerprint",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=64,
                        verbose_name="impressao do conteudo",
                    ),
                ),
                (
                    "markdown_full",
                    models.TextField(blank=True, verbose_name="markdown completo"),
                ),
                (
                    "license",
                    models.CharField(
                        choices=[
                            ("cc_by", "CC BY"),
                            ("cc_by_nc", "CC BY-NC"),
                            ("open_access", "Acesso aberto"),
                            ("proprietary", "Proprietario"),
                            ("own", "Obra propria"),
                            ("unknown", "Desconhecido"),
                        ],
                        default="unknown",
                        max_length=16,
                        verbose_name="licenca",
                    ),
                ),
                (
                    "rights_confirmed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="direitos confirmados em"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Carregado"),
                            ("queued", "Na fila"),
                            ("parsing", "Convertendo"),
                            ("parsed", "Convertido"),
                            ("pending_curation", "Aguardando curadoria"),
                            ("curated", "Curado"),
                            ("embedded", "Indexado"),
                            ("failed", "Falhou"),
                            ("duplicate", "Duplicata"),
                            ("rejected", "Rejeitado"),
                        ],
                        default="uploaded",
                        max_length=20,
                        verbose_name="situacao",
                    ),
                ),
                (
                    "failure_reason",
                    models.TextField(blank=True, verbose_name="motivo da falha"),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="revisado em"
                    ),
                ),
                (
                    "curation_seconds",
                    models.PositiveIntegerField(
                        default=0, verbose_name="segundos de curadoria"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="criado em"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_documents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="revisado por",
                    ),
                ),
                (
                    "rights_confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="direitos confirmados por",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_documents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="carregado por",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents",
                        to="knowledge.documentcategory",
                        verbose_name="categoria",
                    ),
                ),
            ],
            options={
                "verbose_name": "documento",
                "verbose_name_plural": "documentos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SuperChunk",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("abstract", "Resumo"),
                            ("conclusion", "Conclusao"),
                            ("custom", "Outro trecho"),
                        ],
                        max_length=12,
                        verbose_name="tipo",
                    ),
                ),
                ("content", models.TextField(verbose_name="conteudo")),
                (
                    "char_start",
                    models.PositiveIntegerField(default=0, verbose_name="inicio"),
                ),
                (
                    "char_end",
                    models.PositiveIntegerField(default=0, verbose_name="fim"),
                ),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(
                        dimensions=1024, null=True, verbose_name="vetor"
                    ),
                ),
                (
                    "embedding_model",
                    models.CharField(blank=True, max_length=120, verbose_name="modelo"),
                ),
                (
                    "embedding_dim",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="dimensoes"
                    ),
                ),
                (
                    "token_count",
                    models.PositiveSmallIntegerField(default=0, verbose_name="tokens"),
                ),
                (
                    "source_title",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="titulo da fonte"
                    ),
                ),
                (
                    "source_authors",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="autores da fonte"
                    ),
                ),
                (
                    "source_year",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="ano da fonte"
                    ),
                ),
                (
                    "source_url",
                    models.URLField(
                        blank=True, max_length=500, verbose_name="URL da fonte"
                    ),
                ),
                (
                    "source_authority",
                    models.PositiveSmallIntegerField(
                        default=50, verbose_name="autoridade da fonte"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="ativo")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="criado em"
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="knowledge.document",
                        verbose_name="documento",
                    ),
                ),
            ],
            options={
                "verbose_name": "super chunk",
                "verbose_name_plural": "super chunks",
                "ordering": ["document", "kind"],
            },
        ),
        migrations.CreateModel(
            name="RetrievalHit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("distance", models.FloatField(verbose_name="distancia")),
                ("rank", models.PositiveSmallIntegerField(verbose_name="posicao")),
                (
                    "query",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hits",
                        to="knowledge.retrievalquery",
                        verbose_name="consulta",
                    ),
                ),
                (
                    "super_chunk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hits",
                        to="knowledge.superchunk",
                        verbose_name="trecho",
                    ),
                ),
            ],
            options={
                "verbose_name": "resultado de recuperacao",
                "verbose_name_plural": "resultados de recuperacao",
                "ordering": ["query", "rank"],
            },
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["status", "-created_at"], name="knowledge_d_status_f89f13_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["content_fingerprint"], name="knowledge_d_content_40c52a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="superchunk",
            index=models.Index(
                fields=["is_active", "kind"], name="knowledge_s_is_acti_974b55_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="superchunk",
            index=pgvector.django.indexes.HnswIndex(
                ef_construction=64,
                fields=["embedding"],
                m=16,
                name="superchunk_embedding_hnsw",
                opclasses=["vector_cosine_ops"],
            ),
        ),
        migrations.AddConstraint(
            model_name="superchunk",
            constraint=models.UniqueConstraint(
                condition=models.Q(("kind__in", ["abstract", "conclusion"])),
                fields=("document", "kind"),
                name="uniq_chunk_documento_tipo_canonico",
            ),
        ),
        migrations.AddConstraint(
            model_name="retrievalhit",
            constraint=models.UniqueConstraint(
                fields=("query", "rank"), name="uniq_hit_consulta_posicao"
            ),
        ),
    ]
