# Generated by Django 5.2.17 on 2026-08-28 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="extraction_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("docling", "Docling (analise de layout)"),
                    ("pypdf", "Texto do PDF, sem analise de layout"),
                    ("texto", "Arquivo ja em texto"),
                ],
                max_length=16,
                verbose_name="metodo de extracao",
            ),
        ),
    ]
