# Generated by Django 5.2.17 on 2026-08-28 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0002_document_extraction_method"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="superchunk",
            options={
                "ordering": ["document", "block_index", "paragraph_index"],
                "verbose_name": "super chunk",
                "verbose_name_plural": "super chunks",
            },
        ),
        migrations.AddField(
            model_name="superchunk",
            name="block_index",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="bloco"),
        ),
        migrations.AddField(
            model_name="superchunk",
            name="heading",
            field=models.CharField(
                blank=True, max_length=300, verbose_name="titulo do bloco"
            ),
        ),
        migrations.AddField(
            model_name="superchunk",
            name="paragraph_index",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="trecho no bloco"
            ),
        ),
        migrations.AlterField(
            model_name="superchunk",
            name="kind",
            field=models.CharField(
                choices=[
                    ("abstract", "Resumo"),
                    ("conclusion", "Conclusao"),
                    ("custom", "Outro trecho"),
                ],
                default="custom",
                max_length=12,
                verbose_name="tipo",
            ),
        ),
    ]
