# Generated by Django 5.2.17 on 2026-08-28 15:13

import apps.knowledge.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0003_alter_superchunk_options_superchunk_block_index_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RetrievalSettings",
            fields=[
                ("id", models.SmallAutoField(primary_key=True, serialize=False)),
                (
                    "max_cosine_distance",
                    models.FloatField(
                        default=apps.knowledge.models._limiar_padrao,
                        help_text="Acima desta distancia o trecho e descartado. Distancia de cosseno vai de 0 (identico) a 2 (oposto).",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(2.0),
                        ],
                        verbose_name="distancia maxima",
                    ),
                ),
                (
                    "top_k",
                    models.PositiveSmallIntegerField(
                        default=apps.knowledge.models._top_k_padrao,
                        help_text="Quantos documentos distintos, no maximo, sustentam um texto.",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(20),
                        ],
                        verbose_name="fontes por consulta",
                    ),
                ),
                (
                    "calibrated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="calibrado em"
                    ),
                ),
                (
                    "calibrated_model",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="modelo na calibracao"
                    ),
                ),
                (
                    "calibration_query",
                    models.TextField(blank=True, verbose_name="consulta usada"),
                ),
            ],
            options={
                "verbose_name": "configuracao de busca",
                "verbose_name_plural": "configuracao de busca",
            },
        ),
        migrations.AddIndex(
            model_name="retrievalquery",
            index=models.Index(
                fields=["-created_at"], name="knowledge_r_created_96d114_idx"
            ),
        ),
        migrations.AddField(
            model_name="retrievalsettings",
            name="calibrated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="calibrado por",
            ),
        ),
    ]
