# Generated by Django 5.2.17 on 2026-08-28 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0004_retrievalsettings_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="metadata_suggested",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="sugestao da extracao"
            ),
        ),
    ]
