# Generated by Django 5.2.17 on 2026-08-28 22:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0005_document_metadata_suggested"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="extraction_flagged_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="marcado em"
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="extraction_flagged_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="marcado por",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="extraction_note",
            field=models.TextField(blank=True, verbose_name="observacao"),
        ),
        migrations.AddField(
            model_name="document",
            name="extraction_problem",
            field=models.CharField(
                blank=True,
                choices=[
                    ("blocos", "Divisao em blocos errada"),
                    ("texto", "Texto corrompido ou embaralhado"),
                    ("metadados", "Titulo, autores, ano ou DOI errados"),
                    ("outro", "Outro"),
                ],
                max_length=12,
                verbose_name="problema na extracao",
            ),
        ),
    ]
