# Generated by Django 5.2.17 on 2026-09-25 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0006_document_extraction_flagged_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="fetched_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="buscada em"
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="origin",
            field=models.CharField(
                choices=[
                    ("upload", "Arquivo enviado"),
                    ("url", "Pagina por URL"),
                    ("nota", "Nota do especialista"),
                    ("web", "Encontrada na web"),
                    ("youtube", "Video do YouTube"),
                ],
                default="upload",
                max_length=10,
                verbose_name="origem",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="published_on",
            field=models.DateField(blank=True, null=True, verbose_name="publicada em"),
        ),
        migrations.AddField(
            model_name="document",
            name="source_label",
            field=models.CharField(
                blank=True, max_length=300, verbose_name="rotulo da fonte"
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="valid_until",
            field=models.DateField(
                blank=True, db_index=True, null=True, verbose_name="valida ate"
            ),
        ),
        migrations.AddField(
            model_name="documentcategory",
            name="citation_mode",
            field=models.CharField(
                choices=[
                    ("link", "Link para a fonte"),
                    ("atribuicao", "Atribuicao sem link"),
                    ("interna", "Interna (nao aparece no texto)"),
                ],
                default="link",
                max_length=12,
                verbose_name="como citar",
            ),
        ),
        migrations.AddField(
            model_name="documentcategory",
            name="confidential",
            field=models.BooleanField(
                default=False,
                help_text="Pode embasar o texto, mas nunca e citada nem linkada.",
                verbose_name="confidencial",
            ),
        ),
        migrations.AddField(
            model_name="documentcategory",
            name="source_class",
            field=models.CharField(
                choices=[
                    ("cientifico", "Cientifica"),
                    ("normativo", "Normativa ou oficial"),
                    ("empresa", "Material da empresa"),
                    ("especialista", "Especialista"),
                    ("veiculo", "Veiculo de referencia"),
                    ("comunidade", "Comunidade (forum, comentarios)"),
                    ("video", "Video"),
                ],
                default="cientifico",
                max_length=12,
                verbose_name="natureza da fonte",
            ),
        ),
        migrations.AddField(
            model_name="documentcategory",
            name="supports_central_idea",
            field=models.BooleanField(
                default=True,
                help_text="Desligado, a fonte serve para contexto e para entender a duvida, nunca para a afirmacao que o texto existe para fazer.",
                verbose_name="pode sustentar a ideia central",
            ),
        ),
        migrations.AddField(
            model_name="documentcategory",
            name="validity_days",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Tabela de preco e indice mensal vencem; artigo cientifico nao. Vazio: nao vence. Fonte vencida sai da busca ate ser atualizada.",
                null=True,
                verbose_name="validade (dias)",
            ),
        ),
        migrations.AddField(
            model_name="superchunk",
            name="citation_mode",
            field=models.CharField(
                default="link", max_length=12, verbose_name="como citar"
            ),
        ),
        migrations.AddField(
            model_name="superchunk",
            name="source_label",
            field=models.CharField(
                blank=True, max_length=300, verbose_name="rotulo da fonte"
            ),
        ),
        migrations.AddField(
            model_name="superchunk",
            name="supports_central_idea",
            field=models.BooleanField(
                default=True, verbose_name="sustenta a ideia central"
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="extraction_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("docling", "Docling (analise de layout)"),
                    ("pypdf", "Texto do PDF, sem analise de layout"),
                    ("texto", "Arquivo ja em texto"),
                    ("estruturado", "Documento estruturado (DOCX, PPTX, XLSX)"),
                    ("web", "Pagina web (texto principal)"),
                ],
                max_length=16,
                verbose_name="metodo de extracao",
            ),
        ),
    ]
