# Generated by Django 5.2.17 on 2026-09-26 00:22

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


def preencher_indice_textual(apps, schema_editor):
    """Trechos ja indexados ganham o indice textual.

    A normalizacao e a mesma de `normalizar_para_impressao`, copiada aqui:
    migration nao deve importar codigo da aplicacao, que muda depois dela.
    """
    import re
    import unicodedata

    from django.contrib.postgres.search import SearchVector
    from django.db.models import Value

    def normalizar(texto):
        sem_acento = "".join(
            c for c in unicodedata.normalize("NFKD", texto) if not unicodedata.combining(c)
        )
        return re.sub(r"\s+", " ", sem_acento).strip().casefold()

    SuperChunk = apps.get_model("knowledge", "SuperChunk")
    for chunk in SuperChunk.objects.all().iterator():
        partes = [chunk.content, chunk.heading, chunk.source_title, chunk.source_label]
        texto = normalizar(" ".join(p for p in partes if p))
        SuperChunk.objects.filter(pk=chunk.pk).update(
            search_vector=SearchVector(Value(texto), config="simple")
        )


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0007_document_fetched_at_document_origin_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="superchunk",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(
                null=True, verbose_name="indice textual"
            ),
        ),
        migrations.AddIndex(
            model_name="superchunk",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="superchunk_busca_textual_gin"
            ),
        ),
        migrations.RunPython(preencher_indice_textual, migrations.RunPython.noop),
    ]
