# Generated by Django 5.2.17 on 2026-09-26 01:25

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0014_alter_topic_status"),
        ("knowledge", "0008_busca_textual"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="auto_curate",
            field=models.BooleanField(
                default=False, verbose_name="curadoria automatica"
            ),
        ),
        migrations.CreateModel(
            name="CaminhoConfiavel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "prefixo",
                    models.CharField(
                        max_length=300, unique=True, verbose_name="caminho"
                    ),
                ),
                (
                    "nivel",
                    models.CharField(
                        choices=[
                            ("preferir", "Preferir na busca"),
                            ("aprovar", "Aprovar automaticamente"),
                        ],
                        max_length=10,
                        verbose_name="nivel",
                    ),
                ),
                (
                    "observacao",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="observacao"
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="criado em"
                    ),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="caminhos_confiaveis",
                        to="knowledge.documentcategory",
                        verbose_name="categoria",
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="criado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "caminho confiavel",
                "verbose_name_plural": "caminhos confiaveis",
                "ordering": ["prefixo"],
            },
        ),
        migrations.CreateModel(
            name="CandidatoDeFonte",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "url",
                    models.URLField(max_length=500, unique=True, verbose_name="URL"),
                ),
                (
                    "titulo",
                    models.CharField(blank=True, max_length=500, verbose_name="titulo"),
                ),
                ("trecho", models.TextField(blank=True, verbose_name="trecho")),
                (
                    "dominio",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=200,
                        verbose_name="dominio",
                    ),
                ),
                (
                    "consulta",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="consulta"
                    ),
                ),
                (
                    "preferido",
                    models.BooleanField(
                        default=False, verbose_name="de caminho preferido"
                    ),
                ),
                (
                    "situacao",
                    models.CharField(
                        choices=[
                            ("pendente", "Aguardando curadoria"),
                            ("aprovado", "Aprovado"),
                            ("recusado", "Recusado"),
                            ("falhou", "Nao foi possivel buscar"),
                        ],
                        default="pendente",
                        max_length=10,
                        verbose_name="situacao",
                    ),
                ),
                ("motivo", models.TextField(blank=True, verbose_name="motivo")),
                (
                    "decidido_em",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="decidido em"
                    ),
                ),
                (
                    "encontrado_em",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="encontrado em"
                    ),
                ),
                (
                    "decidido_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="decidido por",
                    ),
                ),
                (
                    "documento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="candidatos",
                        to="knowledge.document",
                        verbose_name="documento",
                    ),
                ),
                (
                    "pauta",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="candidatos_de_fonte",
                        to="content.topic",
                        verbose_name="pauta",
                    ),
                ),
            ],
            options={
                "verbose_name": "candidato a fonte",
                "verbose_name_plural": "candidatos a fonte",
                "ordering": ["-preferido", "-encontrado_em"],
            },
        ),
    ]
