# Generated by Django 5.2.17 on 2026-09-26 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0009_document_auto_curate_caminhoconfiavel_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidatodefonte",
            name="canal_id",
            field=models.CharField(blank=True, max_length=100, verbose_name="canal"),
        ),
        migrations.AddField(
            model_name="candidatodefonte",
            name="canal_nome",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="nome do canal"
            ),
        ),
        migrations.AddField(
            model_name="candidatodefonte",
            name="publicado_em",
            field=models.DateField(blank=True, null=True, verbose_name="publicado em"),
        ),
        migrations.AddField(
            model_name="candidatodefonte",
            name="tipo",
            field=models.CharField(
                choices=[("pagina", "Pagina"), ("video", "Video")],
                default="pagina",
                max_length=8,
                verbose_name="tipo",
            ),
        ),
        migrations.AlterField(
            model_name="candidatodefonte",
            name="situacao",
            field=models.CharField(
                choices=[
                    ("pendente", "Aguardando curadoria"),
                    ("aprovado", "Aprovado"),
                    ("recusado", "Recusado"),
                    ("falhou", "Nao foi possivel buscar"),
                    ("audio", "Aguardando o audio"),
                ],
                default="pendente",
                max_length=10,
                verbose_name="situacao",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="extraction_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("docling", "Docling (analise de layout)"),
                    ("pypdf", "Texto do PDF, sem analise de layout"),
                    ("texto", "Arquivo ja em texto"),
                    ("estruturado", "Documento estruturado (DOCX, PPTX, XLSX)"),
                    ("legenda", "Legenda do video"),
                    ("audio", "Audio transcrito"),
                    ("web", "Pagina web (texto principal)"),
                ],
                max_length=16,
                verbose_name="metodo de extracao",
            ),
        ),
    ]
