# Generated by Django 5.2.17 on 2026-09-27 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0010_candidatodefonte_canal_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidatodefonte",
            name="classificacao",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="classificacao"
            ),
        ),
        migrations.AddField(
            model_name="candidatodefonte",
            name="origem",
            field=models.CharField(
                choices=[
                    ("pauta", "Busca de fontes da pauta"),
                    ("radar", "Buscas do radar"),
                ],
                default="pauta",
                max_length=6,
                verbose_name="origem",
            ),
        ),
        migrations.AlterField(
            model_name="caminhoconfiavel",
            name="categoria",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="caminhos_confiaveis",
                to="knowledge.documentcategory",
                verbose_name="categoria",
            ),
        ),
        migrations.AlterField(
            model_name="caminhoconfiavel",
            name="nivel",
            field=models.CharField(
                choices=[
                    ("preferir", "Preferir na busca"),
                    ("aprovar", "Aprovar automaticamente"),
                    ("bloquear", "Nunca sugerir"),
                ],
                max_length=10,
                verbose_name="nivel",
            ),
        ),
    ]
