# Generated by Django 5.2.17 on 2026-09-27 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0011_bloqueio_e_origem_das_fontes"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="replaces",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="replaced_by",
                to="knowledge.document",
                verbose_name="substitui",
            ),
        ),
    ]
