# Generated by Django 5.2.17 on 2026-09-27 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0012_substituicao_de_fonte"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidatodefonte",
            name="texto_extraido",
            field=models.TextField(blank=True, verbose_name="texto extraido"),
        ),
    ]
