# Generated by Django 5.2.17 on 2026-09-28 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0013_texto_extraido"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidatodefonte",
            name="ano",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="ano"
            ),
        ),
        migrations.AddField(
            model_name="candidatodefonte",
            name="autores",
            field=models.CharField(blank=True, max_length=300, verbose_name="autores"),
        ),
        migrations.AddField(
            model_name="candidatodefonte",
            name="citacoes",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="citacoes"
            ),
        ),
        migrations.AddField(
            model_name="candidatodefonte",
            name="doi",
            field=models.CharField(
                blank=True, db_index=True, max_length=200, verbose_name="DOI"
            ),
        ),
        migrations.AddField(
            model_name="candidatodefonte",
            name="pdf_url",
            field=models.URLField(
                blank=True, max_length=500, verbose_name="PDF de acesso aberto"
            ),
        ),
        migrations.AddField(
            model_name="candidatodefonte",
            name="revista",
            field=models.CharField(blank=True, max_length=300, verbose_name="revista"),
        ),
        migrations.AlterField(
            model_name="candidatodefonte",
            name="origem",
            field=models.CharField(
                choices=[
                    ("pauta", "Busca de fontes da pauta"),
                    ("radar", "Buscas do radar"),
                    ("openalex", "Busca de artigos (OpenAlex)"),
                    ("scholar", "Google Academico, nas buscas do radar"),
                ],
                default="pauta",
                max_length=8,
                verbose_name="origem",
            ),
        ),
        migrations.AlterField(
            model_name="candidatodefonte",
            name="situacao",
            field=models.CharField(
                choices=[
                    ("pendente", "Aguardando curadoria"),
                    ("aprovado", "Aprovado"),
                    ("recusado", "Recusado"),
                    ("falhou", "Nao foi possivel buscar"),
                    ("audio", "Aguardando o audio"),
                    ("pdf", "Aguardando o PDF"),
                ],
                default="pendente",
                max_length=10,
                verbose_name="situacao",
            ),
        ),
        migrations.AlterField(
            model_name="candidatodefonte",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("pagina", "Pagina"),
                    ("video", "Video"),
                    ("artigo", "Artigo cientifico"),
                ],
                default="pagina",
                max_length=8,
                verbose_name="tipo",
            ),
        ),
    ]
