# Generated by Django 5.2.17 on 2026-09-30 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0014_artigos_cientificos"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidatodefonte",
            name="metricas",
            field=models.JSONField(blank=True, default=dict, verbose_name="metricas"),
        ),
    ]
