# Generated by Django 5.2.17 on 2026-09-30 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0015_metricas_do_candidato"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="indexacao_erro",
            field=models.TextField(blank=True, verbose_name="erro da indexacao"),
        ),
        migrations.AddField(
            model_name="document",
            name="indexacao_pedida",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="indexacao pedida"
            ),
        ),
    ]
