# Generated by Django 5.2.17 on 2026-09-30 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0016_indexacao_na_fila"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="extraction_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("docling", "Docling (analise de layout)"),
                    ("pypdf", "Texto do PDF, sem analise de layout"),
                    ("texto", "Arquivo ja em texto"),
                    ("estruturado", "Documento estruturado (DOCX, PPTX, XLSX)"),
                    ("legenda", "Legenda do video"),
                    ("audio", "Audio transcrito"),
                    ("web", "Pagina web (texto principal)"),
                    ("resumo", "Resumo do artigo (sem o PDF)"),
                ],
                max_length=16,
                verbose_name="metodo de extracao",
            ),
        ),
    ]
