# Generated by Django 5.2.17 on 2026-10-01 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0017_resumo_do_artigo"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidatodefonte",
            name="documento_completo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="candidatos_pelo_completo",
                to="knowledge.document",
                verbose_name="texto completo",
            ),
        ),
    ]
