# Generated by Django 5.2.17 on 2026-10-02 15:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0018_fluxo_no_artigo"),
    ]

    operations = [
        migrations.CreateModel(
            name="RotuloDeCalibracao",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("consulta", models.CharField(max_length=500, verbose_name="consulta")),
                ("distancia", models.FloatField(verbose_name="distancia")),
                (
                    "rotulo",
                    models.CharField(
                        choices=[
                            ("R", "relevante"),
                            ("I", "irrelevante"),
                            ("L", "lixo"),
                        ],
                        max_length=1,
                        verbose_name="rotulo",
                    ),
                ),
                ("modelo", models.CharField(max_length=120, verbose_name="modelo")),
                (
                    "criado_em",
                    models.DateTimeField(auto_now=True, verbose_name="criado em"),
                ),
                (
                    "trecho",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rotulos",
                        to="knowledge.superchunk",
                        verbose_name="trecho",
                    ),
                ),
            ],
            options={
                "verbose_name": "rotulo de calibracao",
                "verbose_name_plural": "rotulos de calibracao",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("consulta", "trecho"), name="uniq_rotulo_por_consulta"
                    )
                ],
            },
        ),
    ]
