# Generated by Django 5.2.17 on 2026-10-07 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0020_autores_para_citacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidatodefonte",
            name="papel",
            field=models.CharField(
                blank=True,
                choices=[("", "Evidencia"), ("discurso", "Discurso")],
                default="",
                max_length=10,
                verbose_name="papel",
            ),
        ),
    ]
