# Generated by Django 5.2.17 on 2026-10-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0021_candidatodefonte_papel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidatodefonte",
            name="situacao",
            field=models.CharField(
                choices=[
                    ("pendente", "Aguardando curadoria"),
                    ("aprovado", "Aprovado"),
                    ("recusado", "Recusado"),
                    ("fora", "Nao serve para a pauta dela"),
                    ("falhou", "Nao foi possivel buscar"),
                    ("audio", "Aguardando o audio"),
                    ("pdf", "Aguardando o PDF"),
                ],
                default="pendente",
                max_length=10,
                verbose_name="situacao",
            ),
        ),
    ]
