# Generated by Django 5.2.17 on 2026-10-07 06:40

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("content", "0030_topic_debate_alter_topic_origin"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ideia",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("texto", models.TextField(blank=True, verbose_name="a ideia")),
                (
                    "audio",
                    models.FileField(
                        blank=True, max_length=300, upload_to="ideias/audios/%Y/%m/"
                    ),
                ),
                ("transcricao", models.TextField(blank=True)),
                ("links", models.JSONField(blank=True, default=list)),
                (
                    "situacao",
                    models.CharField(
                        choices=[
                            ("nova", "Na fila"),
                            ("audio", "Transcrevendo o audio"),
                            ("lendo", "O modelo esta lendo"),
                            ("buscando", "Buscando fontes"),
                            ("curadoria", "Esperando a sua curadoria"),
                            ("pauta", "Virou pauta"),
                            ("descartada", "Descartada"),
                            ("erro", "Erro"),
                        ],
                        default="nova",
                        max_length=10,
                    ),
                ),
                ("leitura", models.JSONField(blank=True, default=dict)),
                ("buscas", models.JSONField(blank=True, default=dict)),
                (
                    "onde",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("site", "Artigo no site"),
                            ("redes", "Post nas redes"),
                            ("os_dois", "Os dois"),
                        ],
                        max_length=8,
                    ),
                ),
                ("erro", models.TextField(blank=True)),
                ("criada_em", models.DateTimeField(default=django.utils.timezone.now)),
                ("atualizada_em", models.DateTimeField(auto_now=True)),
                (
                    "criada_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pauta",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ideias",
                        to="content.topic",
                    ),
                ),
            ],
            options={
                "ordering": ["-criada_em"],
            },
        ),
    ]
