# Generated by Django 5.2.17 on 2026-10-07 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ideias", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ideia",
            name="situacao",
            field=models.CharField(
                choices=[
                    ("nova", "Na fila"),
                    ("outra_ia", "Esperando a resposta da outra IA"),
                    ("audio", "Transcrevendo o audio"),
                    ("lendo", "O modelo esta lendo"),
                    ("buscando", "Buscando fontes"),
                    ("curadoria", "Esperando a sua curadoria"),
                    ("pauta", "Virou pauta"),
                    ("descartada", "Descartada"),
                    ("erro", "Erro"),
                ],
                default="nova",
                max_length=10,
            ),
        ),
    ]
