# Generated by Django 5.2.17 on 2026-10-07 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ideias", "0002_situacao_outra_ia"),
    ]

    operations = [
        migrations.AddField(
            model_name="ideia",
            name="aprovada_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ideia",
            name="refino",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="ideia",
            name="situacao",
            field=models.CharField(
                choices=[
                    ("nova", "Na fila"),
                    ("outra_ia", "Esperando a resposta da outra IA"),
                    ("audio", "Transcrevendo o audio"),
                    ("lendo", "O modelo esta lendo"),
                    ("buscando", "Buscando fontes"),
                    ("curadoria", "Esperando a sua curadoria"),
                    ("aprovada", "Aprovada"),
                    ("pauta", "Virou pauta"),
                    ("descartada", "Descartada"),
                    ("erro", "Erro"),
                ],
                default="nova",
                max_length=10,
            ),
        ),
    ]
