# Generated by Django 5.2.17 on 2026-09-26 00:54

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import pgvector.django.vector
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("content", "0013_topic_demand_score_topic_evidence_topic_origin"),
    ]

    operations = [
        migrations.CreateModel(
            name="BuscaManual",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("consulta", models.CharField(max_length=500, verbose_name="consulta")),
                (
                    "com_volume",
                    models.BooleanField(default=False, verbose_name="com volume"),
                ),
                (
                    "decisao",
                    models.CharField(
                        choices=[
                            ("pendente", "Aguardando decisao"),
                            ("guardada", "Guardada no radar"),
                            ("descartada", "Descartada"),
                        ],
                        default="pendente",
                        max_length=10,
                        verbose_name="decisao",
                    ),
                ),
                (
                    "resultados",
                    models.JSONField(
                        blank=True, default=list, verbose_name="resultados"
                    ),
                ),
                ("erro", models.TextField(blank=True, verbose_name="erro")),
                (
                    "criado_em",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="em"
                    ),
                ),
            ],
            options={
                "verbose_name": "busca manual",
                "verbose_name_plural": "buscas manuais",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="ChamadaExterna",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "provedor",
                    models.CharField(
                        choices=[
                            ("dataforseo", "DataForSEO"),
                            ("searxng", "SearXNG"),
                            ("youtube", "YouTube"),
                            ("search_console", "Search Console"),
                            ("web", "Pagina web"),
                        ],
                        max_length=16,
                        verbose_name="provedor",
                    ),
                ),
                ("endpoint", models.CharField(max_length=200, verbose_name="endpoint")),
                (
                    "finalidade",
                    models.CharField(
                        choices=[
                            ("radar", "Rodada do radar"),
                            ("manual", "Busca manual"),
                            ("comparacao", "Comparacao de buscadores"),
                            ("fontes", "Busca de fontes"),
                            ("transcricao", "Transcricao"),
                        ],
                        max_length=12,
                        verbose_name="finalidade",
                    ),
                ),
                (
                    "consulta",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="consulta"
                    ),
                ),
                (
                    "custo_usd",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        max_digits=10,
                        verbose_name="custo (US$)",
                    ),
                ),
                (
                    "itens",
                    models.PositiveIntegerField(
                        default=0, verbose_name="itens devolvidos"
                    ),
                ),
                ("sucesso", models.BooleanField(default=True, verbose_name="sucesso")),
                ("erro", models.TextField(blank=True, verbose_name="erro")),
                (
                    "criado_em",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="em",
                    ),
                ),
            ],
            options={
                "verbose_name": "chamada externa",
                "verbose_name_plural": "chamadas externas",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="ComparacaoDeBusca",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("consulta", models.CharField(max_length=500, verbose_name="consulta")),
                (
                    "gratuito",
                    models.CharField(
                        default="searxng", max_length=16, verbose_name="gratuito"
                    ),
                ),
                (
                    "resultados_gratuito",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="resultados (gratuito)"
                    ),
                ),
                (
                    "resultados_pago",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="resultados (pago)"
                    ),
                ),
                (
                    "sobreposicao_urls",
                    models.FloatField(default=0, verbose_name="sobreposicao de URLs"),
                ),
                (
                    "sobreposicao_dominios",
                    models.FloatField(
                        default=0, verbose_name="sobreposicao de dominios"
                    ),
                ),
                (
                    "so_no_pago",
                    models.JSONField(
                        blank=True, default=list, verbose_name="dominios so no pago"
                    ),
                ),
                (
                    "so_no_gratuito",
                    models.JSONField(
                        blank=True, default=list, verbose_name="dominios so no gratuito"
                    ),
                ),
                (
                    "gratuito_falhou",
                    models.BooleanField(default=False, verbose_name="gratuito falhou"),
                ),
                (
                    "criado_em",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="em"
                    ),
                ),
            ],
            options={
                "verbose_name": "comparacao de busca",
                "verbose_name_plural": "comparacoes de busca",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="ConfiguracaoDoRadar",
            fields=[
                ("id", models.SmallAutoField(primary_key=True, serialize=False)),
                (
                    "intensidade",
                    models.CharField(
                        choices=[
                            ("desligado", "Desligado"),
                            ("minimo", "Minimo"),
                            ("normal", "Normal"),
                            ("intenso", "Intenso"),
                        ],
                        default="desligado",
                        max_length=10,
                        verbose_name="intensidade",
                    ),
                ),
                (
                    "usar_serp",
                    models.BooleanField(
                        default=True,
                        help_text="'As pessoas tambem perguntam' e buscas relacionadas. Pago na DataForSEO.",
                        verbose_name="perguntas e buscas relacionadas do Google",
                    ),
                ),
                (
                    "usar_volume",
                    models.BooleanField(
                        default=True,
                        help_text="O mesmo dado do Planejador de palavras-chave do Google Ads.",
                        verbose_name="volume de busca",
                    ),
                ),
                (
                    "usar_perguntas_do_site",
                    models.BooleanField(
                        default=True, verbose_name="perguntas dos visitantes"
                    ),
                ),
                (
                    "usar_youtube",
                    models.BooleanField(
                        default=False, verbose_name="comentarios do YouTube"
                    ),
                ),
                (
                    "usar_search_console",
                    models.BooleanField(default=False, verbose_name="Search Console"),
                ),
                (
                    "buscador",
                    models.CharField(
                        choices=[
                            ("searxng", "SearXNG (gratuito)"),
                            ("dataforseo", "DataForSEO (pago)"),
                        ],
                        default="searxng",
                        max_length=12,
                        verbose_name="buscador",
                    ),
                ),
                (
                    "taxa_de_comparacao",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Com o buscador gratuito, esta fracao das buscas e repetida na DataForSEO e os resultados sao comparados no painel.",
                        validators=[django.core.validators.MaxValueValidator(100)],
                        verbose_name="comparar com o pago (%)",
                    ),
                ),
                (
                    "codigo_de_local",
                    models.PositiveIntegerField(
                        default=2076, verbose_name="codigo de local"
                    ),
                ),
                (
                    "codigo_de_idioma",
                    models.CharField(default="pt", max_length=8, verbose_name="idioma"),
                ),
                (
                    "sementes",
                    models.TextField(
                        blank=True,
                        help_text="Uma por linha: os temas centrais do negocio. O radar parte delas. Ex.: 'planilha de orcamento de obra', 'como calcular BDI'.",
                        verbose_name="palavras-semente",
                    ),
                ),
                (
                    "teto_mensal_usd",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("2.00"),
                        help_text="Atingido o teto, nenhuma chamada paga sai ate o mes virar.",
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="teto mensal (US$)",
                    ),
                ),
                (
                    "ultima_rodada_em",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="ultima rodada"
                    ),
                ),
            ],
            options={
                "verbose_name": "configuracao do radar",
                "verbose_name_plural": "configuracao do radar",
            },
        ),
        migrations.CreateModel(
            name="ContasExternas",
            fields=[
                ("id", models.SmallAutoField(primary_key=True, serialize=False)),
                (
                    "dataforseo_login",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="login DataForSEO"
                    ),
                ),
                (
                    "dataforseo_senha_ciphertext",
                    models.BinaryField(
                        blank=True, null=True, verbose_name="senha DataForSEO (cifrada)"
                    ),
                ),
                (
                    "youtube_chave_ciphertext",
                    models.BinaryField(
                        blank=True, null=True, verbose_name="chave YouTube (cifrada)"
                    ),
                ),
                (
                    "searxng_url",
                    models.URLField(blank=True, max_length=300, verbose_name="SearXNG"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
            ],
            options={
                "verbose_name": "contas externas",
                "verbose_name_plural": "contas externas",
            },
        ),
        migrations.CreateModel(
            name="RodadaDoRadar",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "origem",
                    models.CharField(
                        choices=[
                            ("agendada", "Agendada"),
                            ("manual", "Pedida na tela"),
                        ],
                        max_length=10,
                        verbose_name="origem",
                    ),
                ),
                (
                    "situacao",
                    models.CharField(
                        choices=[
                            ("rodando", "Rodando"),
                            ("concluida", "Concluida"),
                            ("teto", "Parada no teto de custo"),
                            ("falhou", "Falhou"),
                        ],
                        default="rodando",
                        max_length=10,
                        verbose_name="situacao",
                    ),
                ),
                (
                    "iniciada_em",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="iniciada em"
                    ),
                ),
                (
                    "concluida_em",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="concluida em"
                    ),
                ),
                (
                    "custo_usd",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        max_digits=10,
                        verbose_name="custo (US$)",
                    ),
                ),
                (
                    "resumo",
                    models.JSONField(blank=True, default=dict, verbose_name="resumo"),
                ),
                ("erro", models.TextField(blank=True, verbose_name="erro")),
            ],
            options={
                "verbose_name": "rodada do radar",
                "verbose_name_plural": "rodadas do radar",
                "ordering": ["-iniciada_em"],
            },
        ),
        migrations.CreateModel(
            name="GrupoDeDemanda",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("rotulo", models.CharField(max_length=500, verbose_name="rotulo")),
                (
                    "centroide",
                    pgvector.django.vector.VectorField(
                        dimensions=1024, null=True, verbose_name="centroide"
                    ),
                ),
                (
                    "volume_total",
                    models.PositiveIntegerField(
                        default=0, verbose_name="volume somado"
                    ),
                ),
                ("nota", models.FloatField(default=0, verbose_name="nota")),
                (
                    "parcelas",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="parcelas da nota"
                    ),
                ),
                (
                    "situacao",
                    models.CharField(
                        choices=[
                            ("novo", "Novo"),
                            ("pauta", "Virou pauta"),
                            ("descartado", "Descartado"),
                        ],
                        default="novo",
                        max_length=10,
                        verbose_name="situacao",
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "criado_em",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="criado em"
                    ),
                ),
                (
                    "pauta",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="grupos_de_demanda",
                        to="content.topic",
                        verbose_name="pauta",
                    ),
                ),
            ],
            options={
                "verbose_name": "grupo de demanda",
                "verbose_name_plural": "grupos de demanda",
                "ordering": ["-nota"],
            },
        ),
        migrations.CreateModel(
            name="SinalDeDemanda",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("texto", models.CharField(max_length=500, verbose_name="texto")),
                (
                    "fonte",
                    models.CharField(
                        choices=[
                            ("paa", "As pessoas tambem perguntam"),
                            ("relacionada", "Busca relacionada"),
                            ("semente", "Palavra-semente"),
                            ("visitante", "Pergunta de visitante"),
                            ("youtube", "Comentario no YouTube"),
                            ("search_console", "Search Console"),
                            ("manual", "Busca manual"),
                        ],
                        max_length=16,
                        verbose_name="fonte",
                    ),
                ),
                (
                    "volume",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="volume mensal"
                    ),
                ),
                (
                    "extra",
                    models.JSONField(blank=True, default=dict, verbose_name="detalhes"),
                ),
                (
                    "situacao",
                    models.CharField(
                        choices=[
                            ("pendente", "Aguardando decisao"),
                            ("ativo", "Ativo"),
                            ("descartado", "Descartado"),
                        ],
                        default="ativo",
                        max_length=10,
                        verbose_name="situacao",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="em"
                    ),
                ),
                (
                    "busca_manual",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sinais",
                        to="radar.buscamanual",
                        verbose_name="busca manual",
                    ),
                ),
                (
                    "grupo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sinais",
                        to="radar.grupodedemanda",
                        verbose_name="grupo",
                    ),
                ),
                (
                    "rodada",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sinais",
                        to="radar.rodadadoradar",
                        verbose_name="rodada",
                    ),
                ),
            ],
            options={
                "verbose_name": "sinal de demanda",
                "verbose_name_plural": "sinais de demanda",
                "ordering": ["-criado_em"],
                "indexes": [
                    models.Index(
                        fields=["situacao", "grupo"],
                        name="radar_sinal_situaca_cea36a_idx",
                    )
                ],
            },
        ),
    ]
