# Generated by Django 5.2.17 on 2026-09-26 01:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("radar", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracaodoradar",
            name="buscar_fontes",
            field=models.BooleanField(
                default=True,
                help_text="Quando o acervo nao sustenta uma pauta, busca paginas candidatas e as deixa em Documentos > Fontes sugeridas, esperando curadoria.",
                verbose_name="buscar fontes na web para pauta sem cobertura",
            ),
        ),
        migrations.AddField(
            model_name="configuracaodoradar",
            name="fontes_por_pauta",
            field=models.PositiveSmallIntegerField(
                default=5,
                validators=[django.core.validators.MaxValueValidator(20)],
                verbose_name="candidatos por pauta",
            ),
        ),
    ]
