# Generated by Django 5.2.17 on 2026-09-26 01:59

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("radar", "0002_configuracaodoradar_buscar_fontes_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ColetaDoConsole",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "propriedade",
                    models.CharField(max_length=300, verbose_name="propriedade"),
                ),
                ("inicio", models.DateField(verbose_name="inicio")),
                ("fim", models.DateField(verbose_name="fim")),
                (
                    "linhas",
                    models.PositiveIntegerField(default=0, verbose_name="linhas"),
                ),
                (
                    "coletada_em",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="coletada em"
                    ),
                ),
            ],
            options={
                "verbose_name": "coleta do Search Console",
                "verbose_name_plural": "coletas do Search Console",
                "ordering": ["-coletada_em"],
            },
        ),
        migrations.AddField(
            model_name="configuracaodoradar",
            name="propriedade_search_console",
            field=models.CharField(
                blank=True,
                help_text="Como aparece no Search Console: 'sc-domain:exemplo.com.br' (dominio) ou 'https://www.exemplo.com.br/' (prefixo de URL).",
                max_length=300,
                verbose_name="propriedade no Search Console",
            ),
        ),
        migrations.CreateModel(
            name="LinhaDoConsole",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("consulta", models.CharField(max_length=500, verbose_name="consulta")),
                ("pagina", models.URLField(max_length=500, verbose_name="pagina")),
                (
                    "cliques",
                    models.PositiveIntegerField(default=0, verbose_name="cliques"),
                ),
                (
                    "impressoes",
                    models.PositiveIntegerField(default=0, verbose_name="impressoes"),
                ),
                ("ctr", models.FloatField(default=0, verbose_name="CTR")),
                ("posicao", models.FloatField(default=0, verbose_name="posicao media")),
                (
                    "coleta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="linhas_set",
                        to="radar.coletadoconsole",
                        verbose_name="coleta",
                    ),
                ),
            ],
            options={
                "verbose_name": "linha do Search Console",
                "verbose_name_plural": "linhas do Search Console",
                "indexes": [
                    models.Index(
                        fields=["coleta", "pagina"],
                        name="radar_linha_coleta__41c10b_idx",
                    )
                ],
            },
        ),
    ]
