# Generated by Django 5.2.17 on 2026-09-26 07:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("radar", "0003_coletadoconsole_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracaodoradar",
            name="concorrentes",
            field=models.TextField(
                blank=True,
                help_text="Um por linha: 'dominio | nome do negocio no Google'. O nome e opcional e so e usado para as avaliacoes. Ex.: 'clinicax.com.br | Clinica X Curitiba'.",
                verbose_name="concorrentes",
            ),
        ),
        migrations.AddField(
            model_name="configuracaodoradar",
            name="modo_dataforseo",
            field=models.CharField(
                choices=[
                    ("fila", "Fila padrao (mais barata, resultado em minutos)"),
                    ("ao_vivo", "Ao vivo (resultado na hora, ~3x mais caro)"),
                ],
                default="fila",
                help_text="As rodadas nao tem pressa: na fila padrao o resultado chega em alguns minutos, por cerca de um terco do preco. A busca manual e sempre ao vivo.",
                max_length=8,
                verbose_name="modo da DataForSEO nas rodadas",
            ),
        ),
        migrations.AddField(
            model_name="configuracaodoradar",
            name="usar_avaliacoes",
            field=models.BooleanField(
                default=False,
                help_text="Pago (DataForSEO, fila): reclamacoes e perguntas nas avaliacoes do Perfil da Empresa. Para negocio local.",
                verbose_name="avaliacoes dos concorrentes no Google",
            ),
        ),
        migrations.AddField(
            model_name="configuracaodoradar",
            name="usar_concorrentes_buscas",
            field=models.BooleanField(
                default=False,
                help_text="Pago (DataForSEO Labs): palavras em que cada dominio ranqueia.",
                verbose_name="buscas em que os concorrentes aparecem",
            ),
        ),
        migrations.AddField(
            model_name="configuracaodoradar",
            name="usar_concorrentes_conteudo",
            field=models.BooleanField(
                default=False,
                help_text="Gratuito: le o sitemap publico de cada concorrente.",
                verbose_name="o que os concorrentes publicam (sitemap)",
            ),
        ),
        migrations.AddField(
            model_name="rodadadoradar",
            name="fase",
            field=models.CharField(
                default="coleta", max_length=10, verbose_name="fase"
            ),
        ),
        migrations.AlterField(
            model_name="chamadaexterna",
            name="finalidade",
            field=models.CharField(
                choices=[
                    ("radar", "Rodada do radar"),
                    ("manual", "Busca manual"),
                    ("comparacao", "Comparacao de buscadores"),
                    ("fontes", "Busca de fontes"),
                    ("concorrentes", "Concorrentes"),
                    ("transcricao", "Transcricao"),
                ],
                max_length=12,
                verbose_name="finalidade",
            ),
        ),
        migrations.AlterField(
            model_name="rodadadoradar",
            name="situacao",
            field=models.CharField(
                choices=[
                    ("rodando", "Rodando"),
                    ("aguardando", "Aguardando resultados da fila"),
                    ("concluida", "Concluida"),
                    ("teto", "Parada no teto de custo"),
                    ("falhou", "Falhou"),
                ],
                default="rodando",
                max_length=10,
                verbose_name="situacao",
            ),
        ),
        migrations.AlterField(
            model_name="sinaldedemanda",
            name="fonte",
            field=models.CharField(
                choices=[
                    ("paa", "As pessoas tambem perguntam"),
                    ("relacionada", "Busca relacionada"),
                    ("semente", "Palavra-semente"),
                    ("visitante", "Pergunta de visitante"),
                    ("youtube", "Comentario no YouTube"),
                    ("search_console", "Search Console"),
                    ("manual", "Busca manual"),
                    ("conc_conteudo", "Publicado por concorrente"),
                    ("conc_busca", "Busca em que o concorrente aparece"),
                    ("avaliacao", "Avaliacao de concorrente"),
                ],
                max_length=16,
                verbose_name="fonte",
            ),
        ),
        migrations.CreateModel(
            name="TarefaNaFila",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "task_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="id na DataForSEO"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("serp", "Pagina de resultados"),
                            ("volume", "Volume de busca"),
                            ("avaliacoes", "Avaliacoes"),
                        ],
                        max_length=12,
                        verbose_name="tipo",
                    ),
                ),
                (
                    "finalidade",
                    models.CharField(max_length=12, verbose_name="finalidade"),
                ),
                (
                    "contexto",
                    models.JSONField(blank=True, default=dict, verbose_name="contexto"),
                ),
                (
                    "situacao",
                    models.CharField(
                        choices=[
                            ("aguardando", "Aguardando"),
                            ("colhida", "Colhida"),
                            ("falhou", "Falhou"),
                            ("expirada", "Expirada"),
                        ],
                        default="aguardando",
                        max_length=10,
                        verbose_name="situacao",
                    ),
                ),
                ("erro", models.TextField(blank=True, verbose_name="erro")),
                (
                    "criada_em",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="criada em"
                    ),
                ),
                (
                    "colhida_em",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="colhida em"
                    ),
                ),
                (
                    "rodada",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tarefas",
                        to="radar.rodadadoradar",
                        verbose_name="rodada",
                    ),
                ),
            ],
            options={
                "verbose_name": "tarefa na fila",
                "verbose_name_plural": "tarefas na fila",
                "ordering": ["criada_em"],
                "indexes": [
                    models.Index(
                        fields=["situacao", "criada_em"],
                        name="radar_taref_situaca_747ca6_idx",
                    )
                ],
            },
        ),
    ]
