# Generated by Django 5.2.17 on 2026-09-26 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("radar", "0004_fila_e_concorrentes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configuracaodoradar",
            name="buscador",
            field=models.CharField(
                choices=[
                    ("searxng", "SearXNG (gratuito)"),
                    ("dataforseo", "DataForSEO (pago)"),
                ],
                default="dataforseo",
                help_text="O SearXNG so vale se voce hospedar um (SEARXNG_URL). Sem ele configurado, as buscas vao para a DataForSEO de qualquer forma.",
                max_length=12,
                verbose_name="buscador",
            ),
        ),
    ]
