# Generated by Django 5.2.17 on 2026-09-26 16:39

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("radar", "0005_buscador_padrao_pago"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConcorrenteSugerido",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "dominio",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="dominio"
                    ),
                ),
                (
                    "situacao",
                    models.CharField(
                        choices=[
                            ("sugerido", "Sugerido"),
                            ("confirmado", "Confirmado"),
                            ("recusado", "Nao e concorrente"),
                        ],
                        default="sugerido",
                        max_length=10,
                        verbose_name="situacao",
                    ),
                ),
                (
                    "consultas",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="consultas"
                    ),
                ),
                (
                    "exemplos",
                    models.JSONField(blank=True, default=list, verbose_name="exemplos"),
                ),
                (
                    "visto_em",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="visto em"
                    ),
                ),
            ],
            options={
                "verbose_name": "concorrente sugerido",
                "verbose_name_plural": "concorrentes sugeridos",
                "ordering": ["dominio"],
            },
        ),
        migrations.AlterField(
            model_name="configuracaodoradar",
            name="concorrentes",
            field=models.TextField(
                blank=True,
                help_text="Um por linha: 'dominio | nome do negocio no Google'. O nome e opcional e so e usado para as avaliacoes. Ex.: 'clinicax.com.br | Clinica X Curitiba'. Os sugeridos pelo radar e confirmados na tela entram aqui sozinhos.",
                verbose_name="concorrentes",
            ),
        ),
    ]
