# Generated by Django 5.2.17 on 2026-09-26 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("radar", "0006_concorrentes_sugeridos"),
    ]

    operations = [
        migrations.CreateModel(
            name="LocalDisponivel",
            fields=[
                (
                    "codigo",
                    models.PositiveIntegerField(
                        primary_key=True, serialize=False, verbose_name="codigo"
                    ),
                ),
                ("nome", models.CharField(max_length=200, verbose_name="nome")),
                (
                    "tipo",
                    models.CharField(blank=True, max_length=40, verbose_name="tipo"),
                ),
                (
                    "pai",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="local acima"
                    ),
                ),
                (
                    "pais",
                    models.CharField(blank=True, max_length=2, verbose_name="pais"),
                ),
                (
                    "busca",
                    models.CharField(
                        blank=True, db_index=True, max_length=200, verbose_name="busca"
                    ),
                ),
            ],
            options={
                "verbose_name": "local disponivel",
                "verbose_name_plural": "locais disponiveis",
                "ordering": ["nome"],
            },
        ),
        migrations.AddField(
            model_name="configuracaodoradar",
            name="regioes",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Cidades ou estados em que o site quer ser achado. Cada busca e feita em cada regiao (o custo multiplica pelo numero de regioes), e o volume e somado. Vazio = o pais inteiro.",
                verbose_name="regioes",
            ),
        ),
        migrations.AlterField(
            model_name="configuracaodoradar",
            name="codigo_de_local",
            field=models.PositiveIntegerField(
                default=2076,
                help_text="2076 = Brasil. As regioes abaixo refinam as buscas e o volume.",
                verbose_name="pais (codigo)",
            ),
        ),
    ]
