# Generated by Django 5.2.17 on 2026-09-26 23:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("radar", "0007_regioes"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracaodoradar",
            name="dores",
            field=models.TextField(
                blank=True,
                help_text="Uma por linha: problemas que o seu publico sente, nas palavras dele, e NAO os seus servicos. Ex.: 'manchas no rosto', 'clientes somem depois da primeira compra'. Alimentam as Oportunidades: temas que o publico procura e que o site ainda nao oferece.",
                verbose_name="dores do publico",
            ),
        ),
        migrations.AlterField(
            model_name="sinaldedemanda",
            name="fonte",
            field=models.CharField(
                choices=[
                    ("paa", "As pessoas tambem perguntam"),
                    ("relacionada", "Busca relacionada"),
                    ("semente", "Palavra-semente"),
                    ("visitante", "Pergunta de visitante"),
                    ("youtube", "Comentario no YouTube"),
                    ("search_console", "Search Console"),
                    ("manual", "Busca manual"),
                    ("conc_conteudo", "Publicado por concorrente"),
                    ("conc_busca", "Busca em que o concorrente aparece"),
                    ("avaliacao", "Avaliacao de concorrente"),
                    ("dor", "Dor do publico"),
                ],
                max_length=16,
                verbose_name="fonte",
            ),
        ),
        migrations.CreateModel(
            name="Oportunidade",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "situacao",
                    models.CharField(
                        choices=[
                            ("nova", "Nova"),
                            ("acompanhando", "Virou semente"),
                            ("em_teste", "Em teste com artigo"),
                            ("arquivada", "Arquivada"),
                        ],
                        default="nova",
                        max_length=12,
                        verbose_name="situacao",
                    ),
                ),
                ("nota", models.FloatField(default=0, verbose_name="nota")),
                (
                    "parcelas",
                    models.JSONField(blank=True, default=dict, verbose_name="parcelas"),
                ),
                (
                    "termos",
                    models.JSONField(blank=True, default=list, verbose_name="termos"),
                ),
                (
                    "crescimento",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="crescimento"
                    ),
                ),
                (
                    "cpc",
                    models.FloatField(
                        blank=True, null=True, verbose_name="custo por clique (US$)"
                    ),
                ),
                (
                    "descricao",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="descricao"
                    ),
                ),
                (
                    "descricao_em",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="descrita em"
                    ),
                ),
                (
                    "criada_em",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="criada em"
                    ),
                ),
                (
                    "atualizada_em",
                    models.DateTimeField(auto_now=True, verbose_name="atualizada em"),
                ),
                (
                    "grupo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oportunidade",
                        to="radar.grupodedemanda",
                        verbose_name="grupo",
                    ),
                ),
            ],
            options={
                "verbose_name": "oportunidade",
                "verbose_name_plural": "oportunidades",
                "ordering": ["-nota"],
            },
        ),
    ]
