# Generated by Django 5.2.17 on 2026-09-27 00:12

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("radar", "0008_oportunidades"),
    ]

    operations = [
        migrations.CreateModel(
            name="SementeSugerida",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("texto", models.CharField(max_length=200, verbose_name="texto")),
                ("chave", models.CharField(max_length=200, verbose_name="chave")),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("semente", "Palavra-semente"),
                            ("dor", "Dor do publico"),
                        ],
                        max_length=8,
                        verbose_name="tipo",
                    ),
                ),
                (
                    "origem",
                    models.CharField(
                        choices=[
                            ("pagina", "Pagina do site"),
                            ("modelo", "Modelo de linguagem"),
                            ("radar", "Tema forte do radar"),
                        ],
                        max_length=8,
                        verbose_name="origem",
                    ),
                ),
                (
                    "situacao",
                    models.CharField(
                        choices=[
                            ("sugerida", "Sugerida"),
                            ("aceita", "Aceita"),
                            ("recusada", "Recusada"),
                        ],
                        default="sugerida",
                        max_length=9,
                        verbose_name="situacao",
                    ),
                ),
                (
                    "evidencia",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="evidencia"
                    ),
                ),
                (
                    "criada_em",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="criada em"
                    ),
                ),
            ],
            options={
                "verbose_name": "semente sugerida",
                "verbose_name_plural": "sementes sugeridas",
                "ordering": ["tipo", "-criada_em"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("chave", "tipo"), name="semente_sugerida_unica"
                    )
                ],
            },
        ),
    ]
