# Generated by Django 5.2.17 on 2026-09-27 00:27

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0015_alter_prompttemplate_key"),
        ("radar", "0009_sementesugerida"),
    ]

    operations = [
        migrations.CreateModel(
            name="SugestaoDeAtualizacao",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("url", models.URLField(max_length=500, verbose_name="pagina")),
                ("titulo", models.CharField(max_length=300, verbose_name="titulo")),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("acrescentar", "Demanda nova sobre o mesmo tema"),
                            ("quase_la", "Quase na primeira pagina"),
                            ("perdeu", "Perdeu posicao"),
                        ],
                        max_length=12,
                        verbose_name="tipo",
                    ),
                ),
                (
                    "situacao",
                    models.CharField(
                        choices=[
                            ("aberta", "Aberta"),
                            ("feita", "Feita"),
                            ("dispensada", "Dispensada"),
                        ],
                        default="aberta",
                        max_length=10,
                        verbose_name="situacao",
                    ),
                ),
                (
                    "evidencia",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="evidencia"
                    ),
                ),
                ("prioridade", models.FloatField(default=0, verbose_name="prioridade")),
                (
                    "criada_em",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="criada em"
                    ),
                ),
                (
                    "atualizada_em",
                    models.DateTimeField(auto_now=True, verbose_name="atualizada em"),
                ),
                (
                    "decidida_em",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="decidida em"
                    ),
                ),
                (
                    "artigo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sugestoes_de_atualizacao",
                        to="content.article",
                        verbose_name="artigo",
                    ),
                ),
            ],
            options={
                "verbose_name": "sugestao de atualizacao",
                "verbose_name_plural": "sugestoes de atualizacao",
                "ordering": ["-prioridade"],
                "indexes": [
                    models.Index(
                        fields=["situacao", "url", "tipo"],
                        name="radar_suges_situaca_a4e500_idx",
                    )
                ],
            },
        ),
    ]
