# Generated by Django 5.2.17 on 2026-09-27 09:29

import django.db.models.deletion
import django.utils.timezone
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0016_versoes_de_artigo"),
        ("radar", "0010_sugestoes_de_atualizacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracaodoradar",
            name="idade_para_vigiar",
            field=models.PositiveSmallIntegerField(
                default=45,
                help_text="Depois dessa idade, o radar compara cada artigo com os temas novos: demanda com volume tao perto do artigo quanto o tema que o originou vira sugestao de ampliar. Antes disso o Google ainda esta avaliando a pagina, e mexer atrapalha.",
                verbose_name="vigiar artigos publicados ha mais de (dias)",
            ),
        ),
        migrations.CreateModel(
            name="VigiaDeArtigo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "vetor",
                    pgvector.django.vector.VectorField(
                        blank=True, dimensions=1024, null=True, verbose_name="vetor"
                    ),
                ),
                (
                    "distancia_de_referencia",
                    models.FloatField(
                        blank=True, null=True, verbose_name="distancia de referencia"
                    ),
                ),
                (
                    "calculado_em",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="calculado em"
                    ),
                ),
                (
                    "artigo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vigia",
                        to="content.article",
                        verbose_name="artigo",
                    ),
                ),
                (
                    "grupo_de_referencia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="radar.grupodedemanda",
                        verbose_name="tema de referencia",
                    ),
                ),
            ],
            options={
                "verbose_name": "vigia de artigo",
                "verbose_name_plural": "vigias de artigo",
            },
        ),
    ]
