# Generated by Django 5.2.17 on 2026-09-27 09:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("radar", "0011_vigia_de_artigo"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracaodoradar",
            name="fontes_pelo_radar",
            field=models.BooleanField(
                default=True,
                help_text="As paginas que as buscas do radar ja trazem (sem custo extra) viram fonte sugerida — poucas por rodada, so de temas que o acervo ainda nao cobre, e so o que parece artigo. Com muita sugestao esperando decisao, para de sugerir.",
                verbose_name="sugerir fontes a partir das buscas do radar",
            ),
        ),
        migrations.CreateModel(
            name="ResultadoOrganico",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("consulta", models.CharField(max_length=500, verbose_name="consulta")),
                ("url", models.URLField(max_length=500, verbose_name="URL")),
                (
                    "titulo",
                    models.CharField(blank=True, max_length=500, verbose_name="titulo"),
                ),
                ("trecho", models.TextField(blank=True, verbose_name="trecho")),
                ("posicao", models.PositiveSmallIntegerField(verbose_name="posicao")),
                (
                    "criado_em",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="criado em",
                    ),
                ),
                (
                    "rodada",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resultados",
                        to="radar.rodadadoradar",
                        verbose_name="rodada",
                    ),
                ),
            ],
            options={
                "verbose_name": "resultado organico",
                "verbose_name_plural": "resultados organicos",
                "ordering": ["rodada", "consulta", "posicao"],
            },
        ),
    ]
