# Generated by Django 5.2.17 on 2026-09-27 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("radar", "0012_fontes_pelo_radar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sugestaodeatualizacao",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("acrescentar", "Demanda nova sobre o mesmo tema"),
                    ("quase_la", "Quase na primeira pagina"),
                    ("perdeu", "Perdeu posicao"),
                    ("fonte", "Fonte vencida ou substituida"),
                ],
                max_length=12,
                verbose_name="tipo",
            ),
        ),
    ]
