# Generated by Django 5.2.17 on 2026-09-27 16:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("radar", "0013_fonte_vencida"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chamadaexterna",
            name="finalidade",
            field=models.CharField(
                choices=[
                    ("radar", "Rodada do radar"),
                    ("manual", "Busca manual"),
                    ("comparacao", "Comparacao de buscadores"),
                    ("fontes", "Busca de fontes"),
                    ("concorrentes", "Concorrentes"),
                    ("transcricao", "Transcricao"),
                    ("valor", "Valor do trafego"),
                ],
                max_length=12,
                verbose_name="finalidade",
            ),
        ),
        migrations.CreateModel(
            name="CustoDaPalavra",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("palavra", models.CharField(max_length=200, verbose_name="palavra")),
                (
                    "local",
                    models.PositiveIntegerField(default=0, verbose_name="regiao"),
                ),
                (
                    "cpc",
                    models.FloatField(
                        blank=True, null=True, verbose_name="custo por clique (US$)"
                    ),
                ),
                (
                    "volume",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="volume mensal"
                    ),
                ),
                (
                    "competicao",
                    models.FloatField(blank=True, null=True, verbose_name="competicao"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="atualizado em"
                    ),
                ),
            ],
            options={
                "verbose_name": "custo da palavra",
                "verbose_name_plural": "custos das palavras",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("palavra", "local"), name="uniq_custo_por_regiao"
                    )
                ],
            },
        ),
    ]
