# Generated by Django 5.2.17 on 2026-09-27 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("radar", "0014_custo_da_palavra"),
    ]

    operations = [
        migrations.AlterField(
            model_name="oportunidade",
            name="situacao",
            field=models.CharField(
                choices=[
                    ("nova", "Nova"),
                    ("acompanhando", "Virou semente"),
                    ("em_teste", "Em teste com artigo"),
                    ("validada", "Validada: virou frente"),
                    ("arquivada", "Arquivada"),
                ],
                default="nova",
                max_length=12,
                verbose_name="situacao",
            ),
        ),
    ]
