# Generated by Django 5.2.17 on 2026-09-27 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("radar", "0015_oportunidade_validada"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sementesugerida",
            name="origem",
            field=models.CharField(
                choices=[
                    ("pagina", "Pagina do site"),
                    ("modelo", "Modelo de linguagem"),
                    ("radar", "Tema forte do radar"),
                    ("outra_ia", "Outra IA (resposta colada)"),
                ],
                max_length=8,
                verbose_name="origem",
            ),
        ),
    ]
