# Generated by Django 5.2.17 on 2026-09-27 22:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("radar", "0016_origem_outra_ia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configuracaodoradar",
            name="taxa_de_comparacao",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="So vale com o buscador gratuito (SearXNG). Serve para decidir se o gratuito basta: nesta porcentagem das buscas do radar, a mesma busca tambem e feita na DataForSEO (paga), e o painel mostra quanto do resultado pago o gratuito acertou. Ex.: 10% = 1 busca paga a cada 10. Com o buscador DataForSEO, deixe 0.",
                validators=[django.core.validators.MaxValueValidator(100)],
                verbose_name="comparar com o pago (%)",
            ),
        ),
        migrations.AlterField(
            model_name="configuracaodoradar",
            name="usar_youtube",
            field=models.BooleanField(
                default=False,
                help_text="A cada rodada, busca videos das primeiras sementes (minimo: 3, normal: 5, intenso: 10): as perguntas dos comentarios viram sinais, e os videos vao para Documentos > Fontes sugeridas. Gratuito ate a cota do YouTube.",
                verbose_name="comentarios do YouTube",
            ),
        ),
    ]
