# Generated by Django 5.2.17 on 2026-09-27 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("radar", "0017_ajudas_do_youtube_e_da_comparacao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="concorrentesugerido",
            name="situacao",
            field=models.CharField(
                choices=[
                    ("sugerido", "Sugerido"),
                    ("confirmado", "Confirmado"),
                    ("recusado", "Nao e concorrente"),
                    ("parceiro", "Possivel parceiro"),
                ],
                default="sugerido",
                max_length=10,
                verbose_name="situacao",
            ),
        ),
    ]
