# Generated by Django 5.2.17 on 2026-09-27 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("radar", "0018_concorrente_parceiro"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configuracaodoradar",
            name="usar_youtube",
            field=models.BooleanField(
                default=False,
                help_text="A cada rodada, em qualquer intensidade, busca 5 videos de ate 6 sementes: as perguntas dos comentarios viram sinais, e os videos vao para Documentos > Fontes sugeridas. Gratuito; o PubliBot para antes de acabar a cota diaria.",
                verbose_name="comentarios do YouTube",
            ),
        ),
    ]
