# Generated by Django 5.2.17 on 2026-09-28 01:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("radar", "0019_ajuda_do_youtube_sem_intensidade"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracaodoradar",
            name="artigos_cientificos",
            field=models.BooleanField(
                default=True,
                help_text="Gratuito. Busca no OpenAlex (centenas de milhoes de artigos, com resumo e PDF de acesso aberto) para pautas sem fonte e para os temas da rodada que o acervo nao cobre; e aproveita o bloco 'Google Academico' das buscas que o radar ja paga. Tudo espera curadoria em Fontes sugeridas.",
                verbose_name="buscar artigos cientificos",
            ),
        ),
        migrations.AddField(
            model_name="configuracaodoradar",
            name="artigos_por_rodada",
            field=models.PositiveSmallIntegerField(
                default=5,
                validators=[django.core.validators.MaxValueValidator(30)],
                verbose_name="artigos cientificos por rodada",
            ),
        ),
        migrations.AddField(
            model_name="contasexternas",
            name="email_para_bases_academicas",
            field=models.EmailField(
                blank=True,
                help_text="OpenAlex e Unpaywall pedem um e-mail de contato em cada consulta.",
                max_length=254,
                verbose_name="e-mail para as bases academicas",
            ),
        ),
        migrations.AddField(
            model_name="contasexternas",
            name="openalex_chave_ciphertext",
            field=models.BinaryField(
                blank=True, null=True, verbose_name="chave OpenAlex (cifrada)"
            ),
        ),
        migrations.AlterField(
            model_name="chamadaexterna",
            name="provedor",
            field=models.CharField(
                choices=[
                    ("dataforseo", "DataForSEO"),
                    ("searxng", "SearXNG"),
                    ("youtube", "YouTube"),
                    ("search_console", "Search Console"),
                    ("web", "Pagina web"),
                    ("openalex", "OpenAlex"),
                    ("unpaywall", "Unpaywall"),
                ],
                max_length=16,
                verbose_name="provedor",
            ),
        ),
    ]
