# Generated by Django 5.2.17 on 2026-09-28 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("radar", "0020_bases_academicas"),
    ]

    operations = [
        migrations.AddField(
            model_name="concorrentesugerido",
            name="aderencias",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="proximidade das buscas"
            ),
        ),
        migrations.AddField(
            model_name="concorrentesugerido",
            name="imprensa",
            field=models.BooleanField(
                default=False, verbose_name="veiculo de imprensa"
            ),
        ),
    ]
