# Generated by Django 5.2.17 on 2026-09-28 12:41

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0018_autor_padrao"),
        ("radar", "0021_vizinhos_e_imprensa"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaginaVerificada",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "url",
                    models.URLField(max_length=500, unique=True, verbose_name="URL"),
                ),
                (
                    "links",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="links conferidos"
                    ),
                ),
                (
                    "erro",
                    models.CharField(blank=True, max_length=300, verbose_name="erro"),
                ),
                (
                    "verificada_em",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="verificada em",
                    ),
                ),
            ],
            options={
                "verbose_name": "pagina verificada",
                "verbose_name_plural": "paginas verificadas",
            },
        ),
        migrations.AddField(
            model_name="concorrentesugerido",
            name="contatado_em",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="contatado em"
            ),
        ),
        migrations.AddField(
            model_name="configuracaodoradar",
            name="procurar_links_quebrados",
            field=models.BooleanField(
                default=True,
                help_text="Gratuito e devagar: algumas paginas por hora, dos sites que aparecem nas buscas do seu tema. Link que aponta para pagina que nao existe mais, perto de um artigo seu, vira oportunidade de link em Radar > Imprensa e links.",
                verbose_name="procurar links quebrados",
            ),
        ),
        migrations.CreateModel(
            name="LinkQuebrado",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("pagina_url", models.URLField(max_length=500, verbose_name="pagina")),
                (
                    "pagina_titulo",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="titulo da pagina"
                    ),
                ),
                (
                    "dominio",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="dominio"
                    ),
                ),
                (
                    "link_url",
                    models.URLField(max_length=500, verbose_name="link quebrado"),
                ),
                (
                    "texto",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="texto do link"
                    ),
                ),
                (
                    "status_http",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="resposta"
                    ),
                ),
                (
                    "proximidade",
                    models.FloatField(
                        blank=True, null=True, verbose_name="proximidade"
                    ),
                ),
                (
                    "situacao",
                    models.CharField(
                        choices=[
                            ("novo", "Novo"),
                            ("contatado", "Contatado"),
                            ("descartado", "Descartado"),
                        ],
                        default="novo",
                        max_length=10,
                        verbose_name="situacao",
                    ),
                ),
                (
                    "encontrado_em",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="encontrado em"
                    ),
                ),
                (
                    "artigo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="content.article",
                        verbose_name="artigo sugerido",
                    ),
                ),
            ],
            options={
                "verbose_name": "link quebrado",
                "verbose_name_plural": "links quebrados",
                "ordering": ["-encontrado_em"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("pagina_url", "link_url"), name="uniq_link_quebrado"
                    )
                ],
            },
        ),
    ]
