# Generated by Django 5.2.17 on 2026-09-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("radar", "0022_links_quebrados_e_imprensa"),
    ]

    operations = [
        migrations.AddField(
            model_name="grupodedemanda",
            name="avaliacao_ia",
            field=models.CharField(
                blank=True,
                choices=[("", "Sem avaliacao"), ("boa", "Boa"), ("ruim", "Ruim")],
                default="",
                max_length=4,
                verbose_name="avaliacao da IA",
            ),
        ),
        migrations.AddField(
            model_name="grupodedemanda",
            name="avaliado_em",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="avaliado em"
            ),
        ),
        migrations.AddField(
            model_name="grupodedemanda",
            name="motivo_ia",
            field=models.CharField(
                blank=True, max_length=300, verbose_name="motivo da IA"
            ),
        ),
    ]
