# Generated by Django 5.2.17 on 2026-09-29 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("radar", "0023_avaliacao_da_ia"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracaodoradar",
            name="sementes_cientificas",
            field=models.TextField(
                blank=True,
                help_text="Uma por linha: como o assunto aparece em artigo academico — nome de metodo, estrategia, teoria —, de preferencia em ingles. Sao as buscas do OpenAlex; as sementes comerciais trariam lixo. Use o pedido ao lado para uma IA traduzir o seu negocio para o vocabulario academico.",
                verbose_name="sementes cientificas",
            ),
        ),
    ]
