# Generated by Django 5.2.17 on 2026-09-29 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("radar", "0024_sementes_cientificas"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracaodoradar",
            name="estrategia_de_temas",
            field=models.CharField(
                choices=[
                    ("auto", "Automatica (pelo momento do site)"),
                    ("brechas", "Brechas primeiro"),
                    ("equilibrada", "So pela nota"),
                ],
                default="auto",
                help_text="Site comecando, sem autoridade: tema dificil (portais fortes no topo) demora meses, e a brecha entra logo. Em 'brechas primeiro', a dificuldade pesa na ordem dos temas e na escolha das pautas automaticas. Automatica: brechas primeiro ate o Search Console mostrar que os artigos ja chegam ao topo; dai, so pela nota.",
                max_length=12,
                verbose_name="ordem dos temas",
            ),
        ),
    ]
