# Generated by Django 5.2.17 on 2026-09-29 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("radar", "0025_estrategia_de_temas"),
    ]

    operations = [
        migrations.AddField(
            model_name="contasexternas",
            name="saldo_dataforseo",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=12,
                null=True,
                verbose_name="saldo DataForSEO (US$)",
            ),
        ),
        migrations.AddField(
            model_name="contasexternas",
            name="saldo_em",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="saldo lido em"
            ),
        ),
    ]
