# Generated by Django 5.2.17 on 2026-09-30 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("radar", "0026_saldo_dataforseo"),
    ]

    operations = [
        migrations.AddField(
            model_name="linkquebrado",
            name="arquivo_consultado_em",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Internet Archive consultado em"
            ),
        ),
        migrations.AddField(
            model_name="linkquebrado",
            name="arquivo_data",
            field=models.DateField(blank=True, null=True, verbose_name="data da copia"),
        ),
        migrations.AddField(
            model_name="linkquebrado",
            name="arquivo_titulo",
            field=models.CharField(
                blank=True, max_length=300, verbose_name="titulo da pagina que sumiu"
            ),
        ),
        migrations.AddField(
            model_name="linkquebrado",
            name="arquivo_trecho",
            field=models.TextField(
                blank=True, verbose_name="comeco do texto da pagina que sumiu"
            ),
        ),
        migrations.AddField(
            model_name="linkquebrado",
            name="arquivo_url",
            field=models.URLField(
                blank=True, max_length=700, verbose_name="copia no Internet Archive"
            ),
        ),
        migrations.AddField(
            model_name="linkquebrado",
            name="contexto",
            field=models.TextField(blank=True, verbose_name="trecho do artigo"),
        ),
    ]
