# Generated by Django 5.2.17 on 2026-09-30 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0019_link_quebrado_acompanhamento"),
        ("radar", "0027_historico_do_link_quebrado"),
    ]

    operations = [
        migrations.AddField(
            model_name="linkquebrado",
            name="conferido_depois_em",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="conferido depois em"
            ),
        ),
        migrations.AddField(
            model_name="linkquebrado",
            name="conquistado_em",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="conquistado em"
            ),
        ),
        migrations.AddField(
            model_name="linkquebrado",
            name="contatado_em",
            field=models.DateField(blank=True, null=True, verbose_name="contatado em"),
        ),
        migrations.AddField(
            model_name="linkquebrado",
            name="contato_consultado_em",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="contato procurado em"
            ),
        ),
        migrations.AddField(
            model_name="linkquebrado",
            name="contato_email",
            field=models.CharField(
                blank=True, max_length=254, verbose_name="e-mail do site"
            ),
        ),
        migrations.AddField(
            model_name="linkquebrado",
            name="contato_fonte",
            field=models.URLField(
                blank=True, max_length=500, verbose_name="contato achado em"
            ),
        ),
        migrations.AddField(
            model_name="linkquebrado",
            name="contato_whatsapp",
            field=models.CharField(
                blank=True, max_length=30, verbose_name="WhatsApp do site"
            ),
        ),
        migrations.AddField(
            model_name="linkquebrado",
            name="pauta",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="links_quebrados",
                to="content.topic",
                verbose_name="pauta",
            ),
        ),
        migrations.AlterField(
            model_name="linkquebrado",
            name="situacao",
            field=models.CharField(
                choices=[
                    ("novo", "Novo"),
                    ("pauta", "Virou pauta"),
                    ("contatado", "Contatado"),
                    ("conquistado", "Link conquistado"),
                    ("descartado", "Descartado"),
                ],
                default="novo",
                max_length=12,
                verbose_name="situacao",
            ),
        ),
    ]
