# Generated by Django 5.2.17 on 2026-10-01 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("radar", "0029_artigo_parecido"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracaodoradar",
            name="fluxo_da_pesquisa",
            field=models.BooleanField(
                default=True,
                help_text="O sistema pesquisa artigos cientificos para a pauta (busca semantica no OpenAlex), escreve a partir dos resumos e so pede o PDF do que o texto precisar. Menos trabalho antes; a revisao vem no artigo.",
                verbose_name="gerar pela pesquisa de artigos",
            ),
        ),
        migrations.AddField(
            model_name="configuracaodoradar",
            name="fluxo_do_acervo",
            field=models.BooleanField(
                default=True,
                help_text="O caminho de sempre: o artigo usa o que voce curou no acervo. Bom para quem gosta de escolher e curar as fontes antes.",
                verbose_name="gerar pelo acervo",
            ),
        ),
    ]
