# Generated by Django 5.2.17 on 2026-10-01 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("radar", "0030_dois_fluxos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configuracaodoradar",
            name="fluxo_da_pesquisa",
            field=models.BooleanField(
                default=True,
                help_text="O sistema pesquisa artigos cientificos para a pauta (busca semantica no OpenAlex), escreve a partir dos resumos e so le do PDF o que o texto pedir. Com A e B ligados, 'Gerar A e B' faz um de cada para comparar.",
                verbose_name="B · Pesquisa cientifica",
            ),
        ),
        migrations.AlterField(
            model_name="configuracaodoradar",
            name="fluxo_do_acervo",
            field=models.BooleanField(
                default=True,
                help_text="O artigo usa o acervo que voce cura (paginas, videos, artigos, documentos). Bom para quem gosta de escolher e curar as fontes.",
                verbose_name="A · Fontes curadas",
            ),
        ),
    ]
