# Generated by Django 5.2.17 on 2026-10-01 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("radar", "0031_fluxo_no_artigo"),
    ]

    operations = [
        migrations.AddField(
            model_name="linkquebrado",
            name="rechecado_em",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="rechecado em"
            ),
        ),
    ]
