# Generated by Django 5.2.17 on 2026-10-02 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("radar", "0032_rechecar_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chamadaexterna",
            name="finalidade",
            field=models.CharField(
                choices=[
                    ("radar", "Rodada do radar"),
                    ("manual", "Busca manual"),
                    ("comparacao", "Comparacao de buscadores"),
                    ("fontes", "Busca de fontes"),
                    ("concorrentes", "Concorrentes"),
                    ("transcricao", "Transcricao"),
                    ("valor", "Valor do trafego"),
                    ("indexacao", "Indexacao no Google"),
                ],
                max_length=12,
                verbose_name="finalidade",
            ),
        ),
    ]
