# Generated by Django 5.2.17 on 2026-10-07 14:55

from django.db import migrations, models


def artigo_ligado_sozinho_vira_sugestao(apps, schema_editor):
    """Antes, o artigo era ligado sozinho ao link pelo texto do link. Agora so a
    pessoa liga: os que estavam em aberto voltam a ser sugestao, e a tarefa de
    fundo compara de novo com a descricao completa (comparado_em vazio)."""
    LinkQuebrado = apps.get_model("radar", "LinkQuebrado")
    for link in LinkQuebrado.objects.filter(
        situacao="novo", artigo__isnull=False, pauta__isnull=True
    ):
        link.artigo_parecido_id, link.artigo_id = link.artigo_id, None
        link.parecido_proximidade = None
        link.save(update_fields=["artigo", "artigo_parecido", "parecido_proximidade"])


class Migration(migrations.Migration):

    dependencies = [
        ("radar", "0034_sugestao_de_dado_novo"),
    ]

    operations = [
        migrations.AddField(
            model_name="linkquebrado",
            name="artigos_recusados",
            field=models.JSONField(
                blank=True, default=list, verbose_name="artigos que nao servem"
            ),
        ),
        migrations.AddField(
            model_name="linkquebrado",
            name="comparado_em",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="comparado em"
            ),
        ),
        migrations.RunPython(artigo_ligado_sozinho_vira_sugestao, migrations.RunPython.noop),
    ]
