# Generated by Django 5.2.17 on 2026-08-26 19:56

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InferenceConnection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="nome")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("openai_compatible", "Compativel com OpenAI"),
                            ("anthropic", "Anthropic"),
                            ("docling", "Docling (conversao de PDF)"),
                            ("image", "Geracao de imagem"),
                        ],
                        max_length=24,
                        verbose_name="tipo",
                    ),
                ),
                ("base_url", models.URLField(max_length=300, verbose_name="URL base")),
                (
                    "api_key_ciphertext",
                    models.BinaryField(
                        blank=True, null=True, verbose_name="chave (cifrada)"
                    ),
                ),
                (
                    "api_key_last4",
                    models.CharField(
                        blank=True, max_length=4, verbose_name="ultimos 4"
                    ),
                ),
                (
                    "workloads",
                    models.JSONField(
                        default=list,
                        help_text="Lista de Workload que esta conexao sabe executar.",
                        verbose_name="cargas atendidas",
                    ),
                ),
                (
                    "max_concurrency",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="concorrencia maxima",
                    ),
                ),
                (
                    "lease_seconds",
                    models.PositiveIntegerField(
                        default=3600, verbose_name="duracao da reserva"
                    ),
                ),
                (
                    "default_model",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="modelo padrao"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="ativa")),
                (
                    "health_status",
                    models.CharField(
                        choices=[
                            ("unknown", "Desconhecida"),
                            ("healthy", "Saudavel"),
                            ("degraded", "Degradada"),
                            ("down", "Fora do ar"),
                        ],
                        default="unknown",
                        max_length=12,
                        verbose_name="saude",
                    ),
                ),
                (
                    "consecutive_failures",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="falhas seguidas"
                    ),
                ),
                (
                    "circuit_open_until",
                    models.DateTimeField(
                        blank=True,
                        help_text="Enquanto no futuro, nenhuma tarefa tenta usar esta conexao.",
                        null=True,
                        verbose_name="circuito aberto ate",
                    ),
                ),
                (
                    "last_success_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="ultimo sucesso"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="criada em"
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Vazio: conexao compartilhada. Preenchido: exclusiva do tenant.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inference_connections",
                        to="accounts.tenant",
                        verbose_name="tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "conexao de inferencia",
                "verbose_name_plural": "conexoes de inferencia",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="InferenceLease",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "owner_key",
                    models.CharField(
                        help_text="Identificador de quem reservou.",
                        max_length=120,
                        verbose_name="dono",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        blank=True,
                        help_text="Qual modelo esta carregado. Guia o agrupamento do despachante.",
                        max_length=120,
                        verbose_name="modelo",
                    ),
                ),
                (
                    "acquired_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="obtida em"
                    ),
                ),
                ("expires_at", models.DateTimeField(verbose_name="expira em")),
                (
                    "released_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="liberada em"
                    ),
                ),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leases",
                        to="inference.inferenceconnection",
                        verbose_name="conexao",
                    ),
                ),
            ],
            options={
                "verbose_name": "reserva de inferencia",
                "verbose_name_plural": "reservas de inferencia",
            },
        ),
        migrations.AddIndex(
            model_name="inferenceconnection",
            index=models.Index(
                fields=["is_active", "kind"], name="inference_i_is_acti_1883db_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inferencelease",
            index=models.Index(
                fields=["connection", "released_at", "expires_at"],
                name="inference_i_connect_37510c_idx",
            ),
        ),
    ]
