# Generated by Django 5.2.17 on 2026-10-04 15:15

import apps.social.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Abordagem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=80, unique=True, verbose_name="nome"),
                ),
                (
                    "instrucao",
                    models.TextField(
                        help_text="Como escrever com esta abordagem. Vai inteiro no pedido ao modelo.",
                        verbose_name="o que pedir a IA",
                    ),
                ),
                (
                    "redes",
                    models.JSONField(blank=True, default=list, verbose_name="redes"),
                ),
                ("ativa", models.BooleanField(default=True, verbose_name="ativa")),
                ("semente", models.BooleanField(default=False, editable=False)),
                ("criada_em", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name": "abordagem",
                "verbose_name_plural": "abordagens",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="ConfiguracaoSocial",
            fields=[
                ("id", models.SmallAutoField(primary_key=True, serialize=False)),
                (
                    "ligado",
                    models.BooleanField(
                        default=False,
                        help_text="Ligado, o PubliBot escolhe os artigos e escreve os posts uma vez por dia. Desligado, so quando voce pede ('Levar as redes', no artigo).",
                        verbose_name="sugerir posts sozinho",
                    ),
                ),
                (
                    "metrica",
                    models.CharField(
                        choices=[
                            ("cliques", "Cliques no link"),
                            ("conversoes", "Conversoes no site"),
                            (
                                "engajamento",
                                "Engajamento na rede (curtidas, comentarios...)",
                            ),
                        ],
                        default="cliques",
                        help_text="E por esta medida que o PubliBot aprende quais abordagens funcionam em cada rede.",
                        max_length=12,
                        verbose_name="o que conta como sucesso",
                    ),
                ),
                (
                    "variantes",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="2: cada artigo ganha duas versoes (abordagens diferentes) para voce escolher uma — ou publicar as duas em dias diferentes e comparar.",
                        verbose_name="versoes por post",
                    ),
                ),
                (
                    "reciclar_apos_meses",
                    models.PositiveSmallIntegerField(
                        default=3,
                        verbose_name="repostar artigo que converte depois de (meses)",
                    ),
                ),
                (
                    "espacamento_dias",
                    models.PositiveSmallIntegerField(
                        default=30,
                        verbose_name="minimo de dias entre posts do mesmo artigo na mesma rede",
                    ),
                ),
                (
                    "instrucoes",
                    models.TextField(
                        blank=True,
                        help_text="O que vale em qualquer rede: como o negocio quer ser visto, o que evitar, como assinar. Ex.: 'Assine como Dra. Ana, cardiologista'.",
                        verbose_name="instrucoes para todas as redes",
                    ),
                ),
                (
                    "regras",
                    models.TextField(
                        blank=True,
                        default="Sem promessa de resultado ou de cura. Sem urgencia falsa ('so hoje', 'ultimas vagas'). Sem antes e depois. Sem preco como chamariz. So afirme o que o artigo afirma, com os numeros dele.",
                        help_text="Regras do conselho profissional e do negocio. Vao em todo post.",
                        verbose_name="regras que nunca se quebram",
                    ),
                ),
            ],
            options={
                "verbose_name": "configuracao das redes",
            },
        ),
        migrations.CreateModel(
            name="Destino",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("rede", models.CharField(max_length=20, verbose_name="rede")),
                ("nome", models.CharField(max_length=120, verbose_name="nome")),
                (
                    "autor",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="quem posta"
                    ),
                ),
                ("ligado", models.BooleanField(default=True, verbose_name="ligado")),
                (
                    "aprovacao",
                    models.CharField(
                        choices=[
                            ("sempre", "Todo post passa por mim"),
                            ("automatico", "Publicar sozinho no horario"),
                        ],
                        default="sempre",
                        max_length=12,
                        verbose_name="aprovacao",
                    ),
                ),
                (
                    "teto_semanal",
                    models.PositiveSmallIntegerField(
                        default=3, verbose_name="posts por semana, no maximo"
                    ),
                ),
                (
                    "publico",
                    models.TextField(
                        blank=True,
                        help_text="Quem segue e o que espera daqui. Ex.: 'Gestores de clinica e medicos, leem no intervalo, querem dado e opiniao de quem pratica'.",
                        verbose_name="quem esta nesta conta",
                    ),
                ),
                (
                    "tom",
                    models.CharField(blank=True, max_length=200, verbose_name="tom"),
                ),
                (
                    "instrucoes",
                    models.TextField(blank=True, verbose_name="instrucoes desta conta"),
                ),
                (
                    "hashtags_fixas",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="hashtags fixas"
                    ),
                ),
                (
                    "dias",
                    models.JSONField(blank=True, default=list, verbose_name="dias"),
                ),
                (
                    "horarios",
                    models.JSONField(blank=True, default=list, verbose_name="horarios"),
                ),
                (
                    "cores",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="cores das laminas"
                    ),
                ),
                (
                    "chamada_final",
                    models.CharField(
                        blank=True,
                        max_length=160,
                        verbose_name="ultima lamina / chamada",
                    ),
                ),
                (
                    "conta_id",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="id da conta na rede"
                    ),
                ),
                (
                    "conta_nome",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="conta conectada"
                    ),
                ),
                (
                    "credenciais",
                    models.BinaryField(
                        blank=True, null=True, verbose_name="credenciais (cifradas)"
                    ),
                ),
                (
                    "expira_em",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="acesso vence em"
                    ),
                ),
                (
                    "conectado_em",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="conectado em"
                    ),
                ),
                (
                    "ultimo_erro",
                    models.TextField(blank=True, verbose_name="ultimo erro"),
                ),
                (
                    "chave_publica",
                    models.CharField(
                        default=apps.social.models._chave, max_length=40, unique=True
                    ),
                ),
                ("criado_em", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name": "destino",
                "verbose_name_plural": "destinos",
                "ordering": ["rede", "nome"],
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "artigo_id",
                    models.UUIDField(
                        blank=True, db_index=True, null=True, verbose_name="artigo"
                    ),
                ),
                (
                    "artigo_titulo",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="titulo do artigo"
                    ),
                ),
                (
                    "artigo_url",
                    models.URLField(
                        blank=True, max_length=500, verbose_name="endereco do artigo"
                    ),
                ),
                (
                    "motivo",
                    models.CharField(
                        choices=[
                            ("novo", "Artigo novo"),
                            ("subindo", "Quase na primeira pagina do Google"),
                            ("converte", "Artigo que traz clientes"),
                            ("pedido", "Pedido por voce"),
                        ],
                        max_length=10,
                        verbose_name="motivo",
                    ),
                ),
                (
                    "por_que",
                    models.TextField(blank=True, verbose_name="por que este post"),
                ),
                (
                    "situacao",
                    models.CharField(
                        choices=[
                            ("sugerido", "Sugerido"),
                            ("gerando", "Escrevendo"),
                            ("rascunho", "Para revisar"),
                            ("aprovado", "Aprovado (agendado)"),
                            ("publicando", "Publicando"),
                            ("publicado", "Publicado"),
                            ("falhou", "Falhou"),
                            ("descartado", "Descartado"),
                        ],
                        default="sugerido",
                        max_length=10,
                        verbose_name="situacao",
                    ),
                ),
                ("texto", models.TextField(blank=True, verbose_name="texto")),
                (
                    "extras",
                    models.JSONField(blank=True, default=dict, verbose_name="extras"),
                ),
                (
                    "avisos",
                    models.JSONField(blank=True, default=list, verbose_name="avisos"),
                ),
                (
                    "material",
                    models.JSONField(blank=True, default=dict, verbose_name="material"),
                ),
                (
                    "imagens",
                    models.JSONField(blank=True, default=list, verbose_name="imagens"),
                ),
                (
                    "agendado_para",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="agendado para"
                    ),
                ),
                (
                    "publicado_em",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="publicado em"
                    ),
                ),
                (
                    "url_remota",
                    models.URLField(
                        blank=True, max_length=500, verbose_name="endereco do post"
                    ),
                ),
                (
                    "id_remoto",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="id na rede"
                    ),
                ),
                ("erro", models.TextField(blank=True, verbose_name="erro")),
                ("tentativas", models.PositiveSmallIntegerField(default=0)),
                (
                    "cliques",
                    models.PositiveIntegerField(default=0, verbose_name="cliques"),
                ),
                (
                    "metricas",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="resultado"
                    ),
                ),
                (
                    "sucesso",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="funcionou"
                    ),
                ),
                ("aprovado_em", models.DateTimeField(blank=True, null=True)),
                (
                    "chave_publica",
                    models.CharField(
                        default=apps.social.models._chave, max_length=40, unique=True
                    ),
                ),
                ("criado_em", models.DateTimeField(default=django.utils.timezone.now)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "abordagem",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posts",
                        to="social.abordagem",
                    ),
                ),
                (
                    "aprovado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "destino",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="social.destino",
                    ),
                ),
                (
                    "variante_de",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="variantes",
                        to="social.post",
                    ),
                ),
            ],
            options={
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="Comentario",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("id_remoto", models.CharField(max_length=300)),
                (
                    "autor",
                    models.CharField(blank=True, max_length=80, verbose_name="autor"),
                ),
                ("texto", models.TextField(verbose_name="texto")),
                (
                    "escrito_em",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="escrito em"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pergunta", "Pergunta"),
                            ("elogio", "Elogio"),
                            ("reclamacao", "Reclamacao"),
                            ("relato", "Relato"),
                            ("outro", "Outro"),
                        ],
                        max_length=12,
                        verbose_name="tipo",
                    ),
                ),
                ("pergunta_id", models.UUIDField(blank=True, null=True)),
                (
                    "resposta",
                    models.TextField(blank=True, verbose_name="resposta enviada"),
                ),
                ("respondido_em", models.DateTimeField(blank=True, null=True)),
                ("id_da_resposta", models.CharField(blank=True, max_length=300)),
                ("erro", models.TextField(blank=True)),
                ("lido_em", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comentarios",
                        to="social.post",
                    ),
                ),
            ],
            options={
                "ordering": ["-escrito_em"],
            },
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["situacao", "agendado_para"],
                name="social_post_situaca_1dbed4_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="comentario",
            constraint=models.UniqueConstraint(
                fields=("post", "id_remoto"), name="uniq_comentario_por_post"
            ),
        ),
    ]
