# Generated by Django 5.2.17 on 2026-10-05 02:18

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0001_redes"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tema",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("titulo", models.CharField(max_length=400, verbose_name="tema")),
                ("frases", models.JSONField(blank=True, default=list)),
                ("artigos", models.JSONField(blank=True, default=list)),
                ("artigo_principal", models.UUIDField(blank=True, null=True)),
                ("nota", models.FloatField(default=0)),
                ("sinais", models.JSONField(blank=True, default=dict)),
                ("centro", models.JSONField(blank=True, default=list)),
                ("ativo", models.BooleanField(default=True)),
                (
                    "atualizado_em",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "ordering": ["-nota"],
            },
        ),
        migrations.AddField(
            model_name="configuracaosocial",
            name="parametros",
            field=models.JSONField(blank=True, default=dict, verbose_name="parametros"),
        ),
        migrations.AddField(
            model_name="destino",
            name="fase_manual",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="fase (fixar)"
            ),
        ),
        migrations.AddField(
            model_name="destino",
            name="hashtags_de_referencia",
            field=models.CharField(
                blank=True,
                help_text="Instagram: ate 10, separadas por virgula. O PubliBot le os posts que mais engajam nelas (de outras contas) uma vez por semana, para saber que temas e formatos funcionam no nicho antes de voce ter seguidores.",
                max_length=300,
                verbose_name="hashtags de referencia do nicho",
            ),
        ),
        migrations.AddField(
            model_name="destino",
            name="referencias_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="destino",
            name="seguidores",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="seguidores"
            ),
        ),
        migrations.AddField(
            model_name="destino",
            name="seguidores_historico",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="post",
            name="custo_impulso",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                verbose_name="valor do impulso (R$)",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="impulsionado",
            field=models.BooleanField(default=False, verbose_name="impulsionado"),
        ),
        migrations.AddField(
            model_name="post",
            name="impulso_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="configuracaosocial",
            name="metrica",
            field=models.CharField(
                choices=[
                    ("cliques", "Cliques no link"),
                    ("conversoes", "Conversoes no site"),
                    ("engajamento", "Engajamento na rede (curtidas, comentarios...)"),
                    (
                        "taxa",
                        "Taxa sobre o alcance (salvos, compartilhamentos, comentarios, cliques)",
                    ),
                ],
                default="cliques",
                help_text="E por esta medida que o PubliBot aprende quais abordagens funcionam em cada rede.",
                max_length=12,
                verbose_name="o que conta como sucesso",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="motivo",
            field=models.CharField(
                choices=[
                    ("novo", "Artigo novo"),
                    ("subindo", "Quase na primeira pagina do Google"),
                    ("converte", "Artigo que traz clientes"),
                    ("pedido", "Pedido por voce"),
                    ("tema", "Tema que atravessa varios artigos"),
                    ("teste", "Teste pago de abordagem"),
                ],
                max_length=10,
                verbose_name="motivo",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="tema",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="posts",
                to="social.tema",
            ),
        ),
        migrations.CreateModel(
            name="ReferenciaDoNicho",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("hashtag", models.CharField(max_length=80)),
                ("id_remoto", models.CharField(max_length=120)),
                ("legenda", models.TextField(blank=True)),
                ("formato", models.CharField(blank=True, max_length=30)),
                ("curtidas", models.PositiveIntegerField(default=0)),
                ("comentarios", models.PositiveIntegerField(default=0)),
                ("link", models.URLField(blank=True, max_length=500)),
                ("publicado_em", models.DateTimeField(blank=True, null=True)),
                (
                    "coletado_em",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "destino",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referencias",
                        to="social.destino",
                    ),
                ),
            ],
            options={
                "ordering": ["-curtidas"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("destino", "id_remoto"), name="uniq_referencia"
                    )
                ],
            },
        ),
    ]
