# Generated by Django 5.2.17 on 2026-10-05 15:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0002_estrategia"),
    ]

    operations = [
        migrations.AddField(
            model_name="abordagem",
            name="origem",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "PubliBot ou voce"),
                    ("outra_ia", "Sugerida pela outra IA"),
                ],
                default="",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="destino",
            name="anuncios_conta_id",
            field=models.CharField(
                blank=True, max_length=60, verbose_name="conta de anuncios"
            ),
        ),
        migrations.AddField(
            model_name="destino",
            name="anuncios_conta_nome",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="destino",
            name="anuncios_erro",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="destino",
            name="anuncios_planilha_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="destino",
            name="anuncios_sincronizados_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="destino",
            name="erro_de_sincronia",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="destino",
            name="historico_importado_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="destino",
            name="sincronizado_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="motivo",
            field=models.CharField(
                choices=[
                    ("novo", "Artigo novo"),
                    ("subindo", "Quase na primeira pagina do Google"),
                    ("converte", "Artigo que traz clientes"),
                    ("pedido", "Pedido por voce"),
                    ("tema", "Tema que atravessa varios artigos"),
                    ("teste", "Teste pago de abordagem"),
                    ("outra_ia", "Sugerido pela outra IA"),
                    ("historico", "Antes do PubliBot (importado)"),
                ],
                max_length=10,
                verbose_name="motivo",
            ),
        ),
        migrations.CreateModel(
            name="Anuncio",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("id_remoto", models.CharField(max_length=200)),
                (
                    "nome",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="anuncio"
                    ),
                ),
                (
                    "campanha",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="campanha"
                    ),
                ),
                (
                    "objetivo",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="objetivo"
                    ),
                ),
                (
                    "gasto",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="gasto (R$)",
                    ),
                ),
                ("alcance", models.PositiveIntegerField(blank=True, null=True)),
                ("impressoes", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "cliques",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="cliques no link"
                    ),
                ),
                ("resultados", models.PositiveIntegerField(blank=True, null=True)),
                ("inicio", models.DateField(blank=True, null=True)),
                ("fim", models.DateField(blank=True, null=True)),
                ("media_id", models.CharField(blank=True, max_length=120)),
                ("link", models.URLField(blank=True, max_length=500)),
                ("imagem", models.URLField(blank=True, max_length=1000)),
                ("texto", models.TextField(blank=True)),
                (
                    "origem",
                    models.CharField(
                        choices=[
                            ("api", "API da Meta"),
                            ("planilha", "Planilha exportada"),
                        ],
                        max_length=10,
                    ),
                ),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "destino",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anuncios",
                        to="social.destino",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="anuncios",
                        to="social.post",
                    ),
                ),
            ],
            options={
                "ordering": ["-inicio"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("destino", "id_remoto"), name="uniq_anuncio"
                    )
                ],
            },
        ),
    ]
