# Generated by Django 5.2.17 on 2026-10-05 19:46

import apps.social.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0003_historico_anuncios_outra_ia"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Midia",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("foto", "Foto"), ("video", "Video")],
                        default="foto",
                        max_length=6,
                    ),
                ),
                (
                    "arquivo",
                    models.FileField(
                        max_length=300, upload_to=apps.social.models._caminho_da_midia
                    ),
                ),
                ("banco", models.BooleanField(default=False)),
                ("nota", models.TextField(blank=True, verbose_name="nota")),
                ("descricao", models.TextField(blank=True)),
                ("descricao_tentada", models.BooleanField(default=False)),
                ("tirada_em", models.DateTimeField(blank=True, null=True)),
                ("largura", models.PositiveIntegerField(blank=True, null=True)),
                ("altura", models.PositiveIntegerField(blank=True, null=True)),
                ("nitidez", models.FloatField(blank=True, null=True)),
                ("brilho", models.FloatField(blank=True, null=True)),
                ("assinatura", models.CharField(blank=True, max_length=16)),
                ("grupo", models.UUIDField(blank=True, db_index=True, null=True)),
                (
                    "situacao",
                    models.CharField(
                        choices=[
                            ("nova", "No banco"),
                            ("usada", "Ja usada"),
                            ("descartada", "Descartada"),
                        ],
                        default="nova",
                        max_length=10,
                    ),
                ),
                (
                    "motivo",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="por que descartada"
                    ),
                ),
                ("autorizada", models.BooleanField(default=False)),
                ("criada_em", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["tirada_em", "criada_em"],
            },
        ),
        migrations.AddField(
            model_name="configuracaosocial",
            name="descrever_fotos",
            field=models.BooleanField(
                default=False,
                help_text="Foto do banco sem nota ganha uma descricao do que aparece, feita por um modelo que enxerga imagem (precisa de uma conexao de inferencia com modelo de visao). Desligado: a legenda sai da nota e do Negocio.",
                verbose_name="descrever as fotos com o modelo",
            ),
        ),
        migrations.AddField(
            model_name="destino",
            name="fotos_por_cento",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Quanto dos posts automaticos desta conta vem do banco de fotos (o resto, dos artigos). 0: so artigos (consultoria, clinica). 80: quase tudo foto (barbearia, estetica). Entre 1 e 99, o PubliBot ajusta sozinho para o tipo que funciona mais.",
                verbose_name="posts do banco de fotos (%)",
            ),
        ),
        migrations.AddField(
            model_name="destino",
            name="mistura_ajustada_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="motivo",
            field=models.CharField(
                choices=[
                    ("novo", "Artigo novo"),
                    ("subindo", "Quase na primeira pagina do Google"),
                    ("converte", "Artigo que traz clientes"),
                    ("pedido", "Pedido por voce"),
                    ("tema", "Tema que atravessa varios artigos"),
                    ("teste", "Teste pago de abordagem"),
                    ("outra_ia", "Sugerido pela outra IA"),
                    ("caso", "Caso ou novidade sua"),
                    ("fotos", "Do banco de fotos"),
                    ("historico", "Antes do PubliBot (importado)"),
                ],
                max_length=10,
                verbose_name="motivo",
            ),
        ),
        migrations.CreateModel(
            name="Entrada",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("caso", "Caso real"),
                            ("novidade", "Novidade ou bastidor"),
                            ("fotos", "Fotos do trabalho"),
                        ],
                        max_length=10,
                    ),
                ),
                ("texto", models.TextField(blank=True, verbose_name="o que aconteceu")),
                (
                    "audio",
                    models.FileField(
                        blank=True, max_length=300, upload_to="social/audios/%Y/%m/"
                    ),
                ),
                ("transcricao", models.TextField(blank=True)),
                (
                    "situacao_do_audio",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Sem audio"),
                            ("esperando", "Transcrevendo"),
                            ("pronta", "Transcrita"),
                            ("falhou", "Falhou"),
                        ],
                        default="",
                        max_length=10,
                    ),
                ),
                ("artigo_id", models.UUIDField(blank=True, null=True)),
                (
                    "link",
                    models.URLField(blank=True, max_length=500, verbose_name="link"),
                ),
                ("autorizado", models.BooleanField(default=False)),
                ("destinos", models.JSONField(blank=True, default=list)),
                ("criada_em", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "criada_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "midias",
                    models.ManyToManyField(
                        blank=True, related_name="entradas", to="social.midia"
                    ),
                ),
            ],
            options={
                "ordering": ["-criada_em"],
            },
        ),
        migrations.AddField(
            model_name="post",
            name="entrada",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="posts",
                to="social.entrada",
            ),
        ),
    ]
