# Generated by Django 5.2.17 on 2026-10-05 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0004_material_proprio"),
    ]

    operations = [
        migrations.AddField(
            model_name="destino",
            name="usuario_remoto",
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
    ]
