# Generated by Django 5.2.17 on 2026-10-06 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0005_usuario_remoto"),
    ]

    operations = [
        migrations.AddField(
            model_name="destino",
            name="desempenho",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="destino",
            name="historico_planilha_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
