# Generated by Django 5.2.17 on 2026-10-06 22:12

import django.core.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0006_desempenho_e_planilha"),
    ]

    operations = [
        migrations.CreateModel(
            name="Recado",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=80, unique=True, verbose_name="nome"),
                ),
                (
                    "instrucao",
                    models.TextField(
                        help_text="A ideia, nao a frase pronta: o PubliBot escreve com as palavras do post. Ex.: 'aqui o conteudo e checado em estudos, sem sensacionalismo'.",
                        verbose_name="a ideia a passar",
                    ),
                ),
                (
                    "por_cento",
                    models.PositiveSmallIntegerField(
                        default=20,
                        help_text="Em parte dos posts, para comparar com os que ficam sem.",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="em quantos posts (%)",
                    ),
                ),
                (
                    "redes",
                    models.JSONField(blank=True, default=list, verbose_name="redes"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="ativo")),
                ("criado_em", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["nome"],
            },
        ),
        migrations.AddField(
            model_name="entrada",
            name="referencias",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="entrada",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("caso", "Caso real"),
                    ("novidade", "Novidade ou bastidor"),
                    ("comentario", "Noticia ou estudo comentado"),
                    ("fotos", "Fotos do trabalho"),
                ],
                max_length=10,
            ),
        ),
    ]
