# Generated by Django 5.2.17 on 2026-10-07 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0007_links_e_recados"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracaosocial",
            name="link_da_oferta",
            field=models.URLField(
                blank=True,
                help_text="Opcional. Aparece como destino possivel do link de um post, junto da pagina inicial e dos artigos.",
                max_length=500,
                verbose_name="pagina da oferta (landing page)",
            ),
        ),
        migrations.AddField(
            model_name="entrada",
            name="origem",
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
        migrations.AlterField(
            model_name="configuracaosocial",
            name="ligado",
            field=models.BooleanField(
                default=True,
                help_text="Ligado, o PubliBot escolhe os artigos e escreve os posts uma vez por dia. Desligado, so quando voce pede ('Levar as redes', no artigo).",
                verbose_name="sugerir posts sozinho",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="motivo",
            field=models.CharField(
                choices=[
                    ("novo", "Artigo novo"),
                    ("subindo", "Quase na primeira pagina do Google"),
                    ("converte", "Artigo que traz clientes"),
                    ("pedido", "Pedido por voce"),
                    ("tema", "Tema que atravessa varios artigos"),
                    ("teste", "Teste pago de abordagem"),
                    ("outra_ia", "Sugerido pela outra IA"),
                    ("caso", "Caso ou novidade sua"),
                    ("fotos", "Do banco de fotos"),
                    ("historico", "Antes do PubliBot (importado)"),
                    ("ideia", "Ideia aprovada"),
                ],
                max_length=10,
                verbose_name="motivo",
            ),
        ),
    ]
